// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/album/certificate.proto

package album

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CertificateInfo struct {
	Uid                  string   `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Id                   uint64   `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	Created              int64    `protobuf:"varint,3,opt,name=created,proto3" json:"created,omitempty"`
	Updated              int64    `protobuf:"varint,4,opt,name=updated,proto3" json:"updated,omitempty"`
	Creator              string   `protobuf:"bytes,5,opt,name=creator,proto3" json:"creator,omitempty"`
	Operator             string   `protobuf:"bytes,6,opt,name=operator,proto3" json:"operator,omitempty"`
	Sn                   string   `protobuf:"bytes,7,opt,name=sn,proto3" json:"sn,omitempty"`
	Name                 string   `protobuf:"bytes,8,opt,name=name,proto3" json:"name,omitempty"`
	Remark               string   `protobuf:"bytes,9,opt,name=remark,proto3" json:"remark,omitempty"`
	Image                string   `protobuf:"bytes,10,opt,name=image,proto3" json:"image,omitempty"`
	Type                 uint32   `protobuf:"varint,11,opt,name=type,proto3" json:"type,omitempty"`
	Status               uint32   `protobuf:"varint,12,opt,name=status,proto3" json:"status,omitempty"`
	Style                string   `protobuf:"bytes,13,opt,name=style,proto3" json:"style,omitempty"`
	Target               string   `protobuf:"bytes,14,opt,name=target,proto3" json:"target,omitempty"`
	Scene                string   `protobuf:"bytes,15,opt,name=scene,proto3" json:"scene,omitempty"`
	Tags                 []string `protobuf:"bytes,20,rep,name=tags,proto3" json:"tags,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CertificateInfo) Reset()         { *m = CertificateInfo{} }
func (m *CertificateInfo) String() string { return proto.CompactTextString(m) }
func (*CertificateInfo) ProtoMessage()    {}
func (*CertificateInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_91a7d151df1fda2d, []int{0}
}

func (m *CertificateInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CertificateInfo.Unmarshal(m, b)
}
func (m *CertificateInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CertificateInfo.Marshal(b, m, deterministic)
}
func (m *CertificateInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CertificateInfo.Merge(m, src)
}
func (m *CertificateInfo) XXX_Size() int {
	return xxx_messageInfo_CertificateInfo.Size(m)
}
func (m *CertificateInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_CertificateInfo.DiscardUnknown(m)
}

var xxx_messageInfo_CertificateInfo proto.InternalMessageInfo

func (m *CertificateInfo) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *CertificateInfo) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *CertificateInfo) GetCreated() int64 {
	if m != nil {
		return m.Created
	}
	return 0
}

func (m *CertificateInfo) GetUpdated() int64 {
	if m != nil {
		return m.Updated
	}
	return 0
}

func (m *CertificateInfo) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *CertificateInfo) GetOperator() string {
	if m != nil {
		return m.Operator
	}
	return ""
}

func (m *CertificateInfo) GetSn() string {
	if m != nil {
		return m.Sn
	}
	return ""
}

func (m *CertificateInfo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CertificateInfo) GetRemark() string {
	if m != nil {
		return m.Remark
	}
	return ""
}

func (m *CertificateInfo) GetImage() string {
	if m != nil {
		return m.Image
	}
	return ""
}

func (m *CertificateInfo) GetType() uint32 {
	if m != nil {
		return m.Type
	}
	return 0
}

func (m *CertificateInfo) GetStatus() uint32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *CertificateInfo) GetStyle() string {
	if m != nil {
		return m.Style
	}
	return ""
}

func (m *CertificateInfo) GetTarget() string {
	if m != nil {
		return m.Target
	}
	return ""
}

func (m *CertificateInfo) GetScene() string {
	if m != nil {
		return m.Scene
	}
	return ""
}

func (m *CertificateInfo) GetTags() []string {
	if m != nil {
		return m.Tags
	}
	return nil
}

type ReqCertificateAdd struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Remark               string   `protobuf:"bytes,2,opt,name=remark,proto3" json:"remark,omitempty"`
	Location             string   `protobuf:"bytes,3,opt,name=location,proto3" json:"location,omitempty"`
	Operator             string   `protobuf:"bytes,4,opt,name=operator,proto3" json:"operator,omitempty"`
	Type                 uint32   `protobuf:"varint,5,opt,name=type,proto3" json:"type,omitempty"`
	Style                uint32   `protobuf:"varint,6,opt,name=style,proto3" json:"style,omitempty"`
	Targets              []string `protobuf:"bytes,7,rep,name=targets,proto3" json:"targets,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqCertificateAdd) Reset()         { *m = ReqCertificateAdd{} }
func (m *ReqCertificateAdd) String() string { return proto.CompactTextString(m) }
func (*ReqCertificateAdd) ProtoMessage()    {}
func (*ReqCertificateAdd) Descriptor() ([]byte, []int) {
	return fileDescriptor_91a7d151df1fda2d, []int{1}
}

func (m *ReqCertificateAdd) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqCertificateAdd.Unmarshal(m, b)
}
func (m *ReqCertificateAdd) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqCertificateAdd.Marshal(b, m, deterministic)
}
func (m *ReqCertificateAdd) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqCertificateAdd.Merge(m, src)
}
func (m *ReqCertificateAdd) XXX_Size() int {
	return xxx_messageInfo_ReqCertificateAdd.Size(m)
}
func (m *ReqCertificateAdd) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqCertificateAdd.DiscardUnknown(m)
}

var xxx_messageInfo_ReqCertificateAdd proto.InternalMessageInfo

func (m *ReqCertificateAdd) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ReqCertificateAdd) GetRemark() string {
	if m != nil {
		return m.Remark
	}
	return ""
}

func (m *ReqCertificateAdd) GetLocation() string {
	if m != nil {
		return m.Location
	}
	return ""
}

func (m *ReqCertificateAdd) GetOperator() string {
	if m != nil {
		return m.Operator
	}
	return ""
}

func (m *ReqCertificateAdd) GetType() uint32 {
	if m != nil {
		return m.Type
	}
	return 0
}

func (m *ReqCertificateAdd) GetStyle() uint32 {
	if m != nil {
		return m.Style
	}
	return 0
}

func (m *ReqCertificateAdd) GetTargets() []string {
	if m != nil {
		return m.Targets
	}
	return nil
}

type ReqCertificateUpdate struct {
	Uid                  string   `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Remark               string   `protobuf:"bytes,3,opt,name=remark,proto3" json:"remark,omitempty"`
	Cover                string   `protobuf:"bytes,4,opt,name=cover,proto3" json:"cover,omitempty"`
	Operator             string   `protobuf:"bytes,5,opt,name=operator,proto3" json:"operator,omitempty"`
	Passwords            string   `protobuf:"bytes,6,opt,name=passwords,proto3" json:"passwords,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqCertificateUpdate) Reset()         { *m = ReqCertificateUpdate{} }
func (m *ReqCertificateUpdate) String() string { return proto.CompactTextString(m) }
func (*ReqCertificateUpdate) ProtoMessage()    {}
func (*ReqCertificateUpdate) Descriptor() ([]byte, []int) {
	return fileDescriptor_91a7d151df1fda2d, []int{2}
}

func (m *ReqCertificateUpdate) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqCertificateUpdate.Unmarshal(m, b)
}
func (m *ReqCertificateUpdate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqCertificateUpdate.Marshal(b, m, deterministic)
}
func (m *ReqCertificateUpdate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqCertificateUpdate.Merge(m, src)
}
func (m *ReqCertificateUpdate) XXX_Size() int {
	return xxx_messageInfo_ReqCertificateUpdate.Size(m)
}
func (m *ReqCertificateUpdate) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqCertificateUpdate.DiscardUnknown(m)
}

var xxx_messageInfo_ReqCertificateUpdate proto.InternalMessageInfo

func (m *ReqCertificateUpdate) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *ReqCertificateUpdate) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ReqCertificateUpdate) GetRemark() string {
	if m != nil {
		return m.Remark
	}
	return ""
}

func (m *ReqCertificateUpdate) GetCover() string {
	if m != nil {
		return m.Cover
	}
	return ""
}

func (m *ReqCertificateUpdate) GetOperator() string {
	if m != nil {
		return m.Operator
	}
	return ""
}

func (m *ReqCertificateUpdate) GetPasswords() string {
	if m != nil {
		return m.Passwords
	}
	return ""
}

type ReplyCertificateInfo struct {
	Status               *ReplyStatus     `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Info                 *CertificateInfo `protobuf:"bytes,2,opt,name=info,proto3" json:"info,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *ReplyCertificateInfo) Reset()         { *m = ReplyCertificateInfo{} }
func (m *ReplyCertificateInfo) String() string { return proto.CompactTextString(m) }
func (*ReplyCertificateInfo) ProtoMessage()    {}
func (*ReplyCertificateInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_91a7d151df1fda2d, []int{3}
}

func (m *ReplyCertificateInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReplyCertificateInfo.Unmarshal(m, b)
}
func (m *ReplyCertificateInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReplyCertificateInfo.Marshal(b, m, deterministic)
}
func (m *ReplyCertificateInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReplyCertificateInfo.Merge(m, src)
}
func (m *ReplyCertificateInfo) XXX_Size() int {
	return xxx_messageInfo_ReplyCertificateInfo.Size(m)
}
func (m *ReplyCertificateInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_ReplyCertificateInfo.DiscardUnknown(m)
}

var xxx_messageInfo_ReplyCertificateInfo proto.InternalMessageInfo

func (m *ReplyCertificateInfo) GetStatus() *ReplyStatus {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *ReplyCertificateInfo) GetInfo() *CertificateInfo {
	if m != nil {
		return m.Info
	}
	return nil
}

type ReplyCertificateList struct {
	Status               *ReplyStatus       `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	List                 []*CertificateInfo `protobuf:"bytes,2,rep,name=list,proto3" json:"list,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *ReplyCertificateList) Reset()         { *m = ReplyCertificateList{} }
func (m *ReplyCertificateList) String() string { return proto.CompactTextString(m) }
func (*ReplyCertificateList) ProtoMessage()    {}
func (*ReplyCertificateList) Descriptor() ([]byte, []int) {
	return fileDescriptor_91a7d151df1fda2d, []int{4}
}

func (m *ReplyCertificateList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReplyCertificateList.Unmarshal(m, b)
}
func (m *ReplyCertificateList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReplyCertificateList.Marshal(b, m, deterministic)
}
func (m *ReplyCertificateList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReplyCertificateList.Merge(m, src)
}
func (m *ReplyCertificateList) XXX_Size() int {
	return xxx_messageInfo_ReplyCertificateList.Size(m)
}
func (m *ReplyCertificateList) XXX_DiscardUnknown() {
	xxx_messageInfo_ReplyCertificateList.DiscardUnknown(m)
}

var xxx_messageInfo_ReplyCertificateList proto.InternalMessageInfo

func (m *ReplyCertificateList) GetStatus() *ReplyStatus {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *ReplyCertificateList) GetList() []*CertificateInfo {
	if m != nil {
		return m.List
	}
	return nil
}

func init() {
	proto.RegisterType((*CertificateInfo)(nil), "omo.msp.album.CertificateInfo")
	proto.RegisterType((*ReqCertificateAdd)(nil), "omo.msp.album.ReqCertificateAdd")
	proto.RegisterType((*ReqCertificateUpdate)(nil), "omo.msp.album.ReqCertificateUpdate")
	proto.RegisterType((*ReplyCertificateInfo)(nil), "omo.msp.album.ReplyCertificateInfo")
	proto.RegisterType((*ReplyCertificateList)(nil), "omo.msp.album.ReplyCertificateList")
}

func init() {
	proto.RegisterFile("proto/album/certificate.proto", fileDescriptor_91a7d151df1fda2d)
}

var fileDescriptor_91a7d151df1fda2d = []byte{
	// 668 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x55, 0x51, 0x6e, 0xda, 0x4c,
	0x10, 0x8e, 0x0d, 0x98, 0x30, 0x84, 0xe4, 0xff, 0x57, 0x51, 0xb5, 0x42, 0x49, 0x85, 0xe8, 0x0b,
	0x4f, 0x44, 0xa2, 0x27, 0x20, 0x51, 0x83, 0xd2, 0xb4, 0xaa, 0x6a, 0xd4, 0x3e, 0xf4, 0x6d, 0x63,
	0x4f, 0xe8, 0xaa, 0xd8, 0xeb, 0x78, 0x97, 0x54, 0xbc, 0xf4, 0x34, 0xbd, 0x45, 0x2f, 0xd3, 0x3b,
	0xf4, 0x02, 0xd5, 0x8e, 0x8d, 0x03, 0x8e, 0x93, 0xa0, 0xe6, 0xcd, 0xdf, 0xcc, 0xb7, 0xdf, 0xcc,
	0x37, 0x33, 0x08, 0x38, 0x4e, 0x52, 0x65, 0xd4, 0x89, 0x98, 0x5f, 0x2d, 0xa2, 0x93, 0x00, 0x53,
	0x23, 0xaf, 0x65, 0x20, 0x0c, 0x0e, 0x29, 0xce, 0x3a, 0x2a, 0x52, 0xc3, 0x48, 0x27, 0x43, 0x22,
	0x74, 0xf9, 0x06, 0x5b, 0x45, 0x91, 0x8a, 0x33, 0x62, 0xff, 0x8f, 0x0b, 0x07, 0x67, 0x77, 0xcf,
	0x2f, 0xe2, 0x6b, 0xc5, 0xfe, 0x83, 0xda, 0x42, 0x86, 0xdc, 0xe9, 0x39, 0x83, 0x96, 0x6f, 0x3f,
	0xd9, 0x3e, 0xb8, 0x32, 0xe4, 0x6e, 0xcf, 0x19, 0xd4, 0x7d, 0x57, 0x86, 0x8c, 0x43, 0x33, 0x48,
	0x51, 0x18, 0x0c, 0x79, 0xad, 0xe7, 0x0c, 0x6a, 0xfe, 0x0a, 0xda, 0xcc, 0x22, 0x09, 0x29, 0x53,
	0xcf, 0x32, 0x39, 0x2c, 0xde, 0xa8, 0x94, 0x37, 0x48, 0x79, 0x05, 0x59, 0x17, 0x76, 0x55, 0x82,
	0x29, 0xa5, 0x3c, 0x4a, 0x15, 0xd8, 0x56, 0xd6, 0x31, 0x6f, 0x52, 0xd4, 0xd5, 0x31, 0x63, 0x50,
	0x8f, 0x45, 0x84, 0x7c, 0x97, 0x22, 0xf4, 0xcd, 0x5e, 0x80, 0x97, 0x62, 0x24, 0xd2, 0x6f, 0xbc,
	0x45, 0xd1, 0x1c, 0xb1, 0x43, 0x68, 0xc8, 0x48, 0xcc, 0x90, 0x03, 0x85, 0x33, 0x60, 0x15, 0xcc,
	0x32, 0x41, 0xde, 0xee, 0x39, 0x83, 0x8e, 0x4f, 0xdf, 0x56, 0x41, 0x1b, 0x61, 0x16, 0x9a, 0xef,
	0x51, 0x34, 0x47, 0x56, 0x41, 0x9b, 0xe5, 0x1c, 0x79, 0x27, 0x53, 0x20, 0x60, 0xd9, 0x46, 0xa4,
	0x33, 0x34, 0x7c, 0x3f, 0xab, 0x97, 0x21, 0x62, 0x07, 0x18, 0x23, 0x3f, 0xc8, 0xd9, 0x16, 0x50,
	0x3d, 0x31, 0xd3, 0xfc, 0xb0, 0x57, 0xb3, 0x1d, 0xdb, 0xef, 0xfe, 0x2f, 0x07, 0xfe, 0xf7, 0xf1,
	0x66, 0x6d, 0xf0, 0xe3, 0x30, 0x2c, 0xbc, 0x39, 0x95, 0xde, 0xdc, 0x0d, 0x6f, 0x5d, 0xd8, 0x9d,
	0xab, 0x40, 0x18, 0xa9, 0x62, 0x5a, 0x41, 0xcb, 0x2f, 0xf0, 0xc6, 0x3c, 0xeb, 0xa5, 0x79, 0xae,
	0xdc, 0x37, 0xd6, 0xdc, 0x17, 0x2e, 0x3d, 0x0a, 0xe6, 0x2e, 0x39, 0x34, 0x33, 0x5f, 0x9a, 0x37,
	0xa9, 0xf5, 0x15, 0xec, 0xff, 0x74, 0xe0, 0x70, 0xb3, 0xfb, 0x4f, 0xb4, 0xe3, 0x8a, 0xc3, 0x59,
	0x59, 0x72, 0x2b, 0x2d, 0xd5, 0xca, 0xeb, 0x0a, 0xd4, 0x2d, 0xae, 0x7a, 0xce, 0xc0, 0x86, 0x99,
	0x46, 0xc9, 0xcc, 0x11, 0xb4, 0x12, 0xa1, 0xf5, 0x77, 0x95, 0x86, 0x3a, 0xbf, 0x9c, 0xbb, 0x40,
	0xff, 0x87, 0xed, 0x32, 0x99, 0x2f, 0xcb, 0xe7, 0x3d, 0x2a, 0x96, 0x6d, 0x1b, 0x6d, 0x8f, 0xba,
	0xc3, 0x8d, 0x1f, 0xcb, 0x90, 0x1e, 0x4d, 0x89, 0x51, 0x1c, 0xc2, 0x08, 0xea, 0x32, 0xbe, 0x56,
	0xe4, 0xa3, 0x3d, 0x7a, 0x59, 0x7a, 0x51, 0xaa, 0xe0, 0x13, 0xb7, 0xaa, 0xfe, 0x3b, 0xa9, 0xcd,
	0xbf, 0xd6, 0x9f, 0x4b, 0x6d, 0xb8, 0xdb, 0xab, 0x6d, 0x53, 0xdf, 0x72, 0x47, 0xbf, 0x3d, 0x60,
	0x6b, 0x99, 0x29, 0xa6, 0xb7, 0x32, 0x40, 0xf6, 0x11, 0xbc, 0x71, 0x18, 0x7e, 0x88, 0x91, 0xf5,
	0xee, 0x15, 0x2e, 0x5d, 0x64, 0xf7, 0x55, 0x55, 0x6b, 0xa5, 0x6a, 0xfd, 0x1d, 0xf6, 0x16, 0x20,
	0xbb, 0x80, 0x53, 0xa1, 0xb7, 0x91, 0xe5, 0x55, 0xb2, 0xb9, 0xd6, 0x19, 0xb4, 0x7c, 0x8c, 0xd4,
	0x2d, 0xda, 0x0e, 0xef, 0x8f, 0xe6, 0x66, 0x81, 0xda, 0x58, 0xea, 0xa3, 0x22, 0x97, 0xe0, 0x4d,
	0xd0, 0x3c, 0xa5, 0xb0, 0xa5, 0xbb, 0x4b, 0xf0, 0xa6, 0x28, 0xd2, 0xe0, 0xeb, 0xb3, 0xc4, 0xec,
	0xea, 0xfb, 0x3b, 0xec, 0x33, 0x1c, 0x4c, 0xd0, 0x58, 0x70, 0xba, 0x3c, 0x97, 0x73, 0x83, 0x29,
	0x3b, 0xaa, 0x56, 0xcd, 0xb2, 0xdb, 0xea, 0xbe, 0x87, 0xbd, 0x09, 0x1a, 0x7b, 0x35, 0x52, 0x1b,
	0x19, 0x3c, 0x21, 0x7a, 0xfc, 0xd0, 0xc9, 0xd1, 0x63, 0xda, 0xe8, 0x7e, 0xbe, 0xd1, 0x27, 0xba,
	0xcc, 0x58, 0x8f, 0x2e, 0xe3, 0x02, 0xf6, 0x32, 0x56, 0x76, 0xd3, 0xec, 0xf8, 0xa1, 0x29, 0x9a,
	0xf3, 0xb9, 0x98, 0x3d, 0x2a, 0xf5, 0x06, 0xda, 0xe3, 0x24, 0xc1, 0x38, 0x1c, 0x6b, 0x8d, 0xe6,
	0xa1, 0x7d, 0xd8, 0x91, 0x54, 0xcb, 0xe4, 0xc3, 0x9a, 0x40, 0x67, 0xba, 0xb8, 0x32, 0xa9, 0x08,
	0xcc, 0xb3, 0x84, 0x4e, 0x3b, 0x5f, 0xda, 0x6b, 0xff, 0xac, 0x57, 0x1e, 0x81, 0xd7, 0x7f, 0x03,
	0x00, 0x00, 0xff, 0xff, 0x6e, 0xe5, 0x89, 0x44, 0x9d, 0x07, 0x00, 0x00,
}
