// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/album/collective.proto

package album

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CollectiveInfo struct {
	Uid                  string        `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Id                   uint64        `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	Created              int64         `protobuf:"varint,3,opt,name=created,proto3" json:"created,omitempty"`
	Updated              int64         `protobuf:"varint,4,opt,name=updated,proto3" json:"updated,omitempty"`
	Creator              string        `protobuf:"bytes,5,opt,name=creator,proto3" json:"creator,omitempty"`
	Operator             string        `protobuf:"bytes,6,opt,name=operator,proto3" json:"operator,omitempty"`
	Name                 string        `protobuf:"bytes,7,opt,name=name,proto3" json:"name,omitempty"`
	Remark               string        `protobuf:"bytes,8,opt,name=remark,proto3" json:"remark,omitempty"`
	Cover                string        `protobuf:"bytes,9,opt,name=cover,proto3" json:"cover,omitempty"`
	Owner                string        `protobuf:"bytes,10,opt,name=owner,proto3" json:"owner,omitempty"`
	Size                 uint64        `protobuf:"varint,11,opt,name=size,proto3" json:"size,omitempty"`
	Limit                uint32        `protobuf:"varint,12,opt,name=limit,proto3" json:"limit,omitempty"`
	Star                 uint32        `protobuf:"varint,13,opt,name=star,proto3" json:"star,omitempty"`
	Status               uint32        `protobuf:"varint,14,opt,name=status,proto3" json:"status,omitempty"`
	Permission           uint32        `protobuf:"varint,15,opt,name=permission,proto3" json:"permission,omitempty"`
	Type                 uint32        `protobuf:"varint,16,opt,name=type,proto3" json:"type,omitempty"`
	Duration             *DurationInfo `protobuf:"bytes,17,opt,name=duration,proto3" json:"duration,omitempty"`
	Assets               []string      `protobuf:"bytes,21,rep,name=assets,proto3" json:"assets,omitempty"`
	Tags                 []string      `protobuf:"bytes,22,rep,name=tags,proto3" json:"tags,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *CollectiveInfo) Reset()         { *m = CollectiveInfo{} }
func (m *CollectiveInfo) String() string { return proto.CompactTextString(m) }
func (*CollectiveInfo) ProtoMessage()    {}
func (*CollectiveInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_81657e36c0b4b126, []int{0}
}

func (m *CollectiveInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CollectiveInfo.Unmarshal(m, b)
}
func (m *CollectiveInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CollectiveInfo.Marshal(b, m, deterministic)
}
func (m *CollectiveInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CollectiveInfo.Merge(m, src)
}
func (m *CollectiveInfo) XXX_Size() int {
	return xxx_messageInfo_CollectiveInfo.Size(m)
}
func (m *CollectiveInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_CollectiveInfo.DiscardUnknown(m)
}

var xxx_messageInfo_CollectiveInfo proto.InternalMessageInfo

func (m *CollectiveInfo) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *CollectiveInfo) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *CollectiveInfo) GetCreated() int64 {
	if m != nil {
		return m.Created
	}
	return 0
}

func (m *CollectiveInfo) GetUpdated() int64 {
	if m != nil {
		return m.Updated
	}
	return 0
}

func (m *CollectiveInfo) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *CollectiveInfo) GetOperator() string {
	if m != nil {
		return m.Operator
	}
	return ""
}

func (m *CollectiveInfo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CollectiveInfo) GetRemark() string {
	if m != nil {
		return m.Remark
	}
	return ""
}

func (m *CollectiveInfo) GetCover() string {
	if m != nil {
		return m.Cover
	}
	return ""
}

func (m *CollectiveInfo) GetOwner() string {
	if m != nil {
		return m.Owner
	}
	return ""
}

func (m *CollectiveInfo) GetSize() uint64 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *CollectiveInfo) GetLimit() uint32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *CollectiveInfo) GetStar() uint32 {
	if m != nil {
		return m.Star
	}
	return 0
}

func (m *CollectiveInfo) GetStatus() uint32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *CollectiveInfo) GetPermission() uint32 {
	if m != nil {
		return m.Permission
	}
	return 0
}

func (m *CollectiveInfo) GetType() uint32 {
	if m != nil {
		return m.Type
	}
	return 0
}

func (m *CollectiveInfo) GetDuration() *DurationInfo {
	if m != nil {
		return m.Duration
	}
	return nil
}

func (m *CollectiveInfo) GetAssets() []string {
	if m != nil {
		return m.Assets
	}
	return nil
}

func (m *CollectiveInfo) GetTags() []string {
	if m != nil {
		return m.Tags
	}
	return nil
}

type ReqCollectiveAdd struct {
	Name                 string        `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Remark               string        `protobuf:"bytes,2,opt,name=remark,proto3" json:"remark,omitempty"`
	Operator             string        `protobuf:"bytes,3,opt,name=operator,proto3" json:"operator,omitempty"`
	Owner                string        `protobuf:"bytes,4,opt,name=owner,proto3" json:"owner,omitempty"`
	Type                 uint32        `protobuf:"varint,5,opt,name=type,proto3" json:"type,omitempty"`
	Duration             *DurationInfo `protobuf:"bytes,11,opt,name=duration,proto3" json:"duration,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *ReqCollectiveAdd) Reset()         { *m = ReqCollectiveAdd{} }
func (m *ReqCollectiveAdd) String() string { return proto.CompactTextString(m) }
func (*ReqCollectiveAdd) ProtoMessage()    {}
func (*ReqCollectiveAdd) Descriptor() ([]byte, []int) {
	return fileDescriptor_81657e36c0b4b126, []int{1}
}

func (m *ReqCollectiveAdd) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqCollectiveAdd.Unmarshal(m, b)
}
func (m *ReqCollectiveAdd) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqCollectiveAdd.Marshal(b, m, deterministic)
}
func (m *ReqCollectiveAdd) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqCollectiveAdd.Merge(m, src)
}
func (m *ReqCollectiveAdd) XXX_Size() int {
	return xxx_messageInfo_ReqCollectiveAdd.Size(m)
}
func (m *ReqCollectiveAdd) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqCollectiveAdd.DiscardUnknown(m)
}

var xxx_messageInfo_ReqCollectiveAdd proto.InternalMessageInfo

func (m *ReqCollectiveAdd) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ReqCollectiveAdd) GetRemark() string {
	if m != nil {
		return m.Remark
	}
	return ""
}

func (m *ReqCollectiveAdd) GetOperator() string {
	if m != nil {
		return m.Operator
	}
	return ""
}

func (m *ReqCollectiveAdd) GetOwner() string {
	if m != nil {
		return m.Owner
	}
	return ""
}

func (m *ReqCollectiveAdd) GetType() uint32 {
	if m != nil {
		return m.Type
	}
	return 0
}

func (m *ReqCollectiveAdd) GetDuration() *DurationInfo {
	if m != nil {
		return m.Duration
	}
	return nil
}

type ReqCollectiveUpdate struct {
	Uid                  string   `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Remark               string   `protobuf:"bytes,3,opt,name=remark,proto3" json:"remark,omitempty"`
	Cover                string   `protobuf:"bytes,4,opt,name=cover,proto3" json:"cover,omitempty"`
	Operator             string   `protobuf:"bytes,5,opt,name=operator,proto3" json:"operator,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqCollectiveUpdate) Reset()         { *m = ReqCollectiveUpdate{} }
func (m *ReqCollectiveUpdate) String() string { return proto.CompactTextString(m) }
func (*ReqCollectiveUpdate) ProtoMessage()    {}
func (*ReqCollectiveUpdate) Descriptor() ([]byte, []int) {
	return fileDescriptor_81657e36c0b4b126, []int{2}
}

func (m *ReqCollectiveUpdate) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqCollectiveUpdate.Unmarshal(m, b)
}
func (m *ReqCollectiveUpdate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqCollectiveUpdate.Marshal(b, m, deterministic)
}
func (m *ReqCollectiveUpdate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqCollectiveUpdate.Merge(m, src)
}
func (m *ReqCollectiveUpdate) XXX_Size() int {
	return xxx_messageInfo_ReqCollectiveUpdate.Size(m)
}
func (m *ReqCollectiveUpdate) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqCollectiveUpdate.DiscardUnknown(m)
}

var xxx_messageInfo_ReqCollectiveUpdate proto.InternalMessageInfo

func (m *ReqCollectiveUpdate) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *ReqCollectiveUpdate) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ReqCollectiveUpdate) GetRemark() string {
	if m != nil {
		return m.Remark
	}
	return ""
}

func (m *ReqCollectiveUpdate) GetCover() string {
	if m != nil {
		return m.Cover
	}
	return ""
}

func (m *ReqCollectiveUpdate) GetOperator() string {
	if m != nil {
		return m.Operator
	}
	return ""
}

type ReplyCollectiveInfo struct {
	Status               *ReplyStatus    `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Info                 *CollectiveInfo `protobuf:"bytes,2,opt,name=info,proto3" json:"info,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *ReplyCollectiveInfo) Reset()         { *m = ReplyCollectiveInfo{} }
func (m *ReplyCollectiveInfo) String() string { return proto.CompactTextString(m) }
func (*ReplyCollectiveInfo) ProtoMessage()    {}
func (*ReplyCollectiveInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_81657e36c0b4b126, []int{3}
}

func (m *ReplyCollectiveInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReplyCollectiveInfo.Unmarshal(m, b)
}
func (m *ReplyCollectiveInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReplyCollectiveInfo.Marshal(b, m, deterministic)
}
func (m *ReplyCollectiveInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReplyCollectiveInfo.Merge(m, src)
}
func (m *ReplyCollectiveInfo) XXX_Size() int {
	return xxx_messageInfo_ReplyCollectiveInfo.Size(m)
}
func (m *ReplyCollectiveInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_ReplyCollectiveInfo.DiscardUnknown(m)
}

var xxx_messageInfo_ReplyCollectiveInfo proto.InternalMessageInfo

func (m *ReplyCollectiveInfo) GetStatus() *ReplyStatus {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *ReplyCollectiveInfo) GetInfo() *CollectiveInfo {
	if m != nil {
		return m.Info
	}
	return nil
}

type ReplyCollectiveList struct {
	Status               *ReplyStatus      `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	List                 []*CollectiveInfo `protobuf:"bytes,2,rep,name=list,proto3" json:"list,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *ReplyCollectiveList) Reset()         { *m = ReplyCollectiveList{} }
func (m *ReplyCollectiveList) String() string { return proto.CompactTextString(m) }
func (*ReplyCollectiveList) ProtoMessage()    {}
func (*ReplyCollectiveList) Descriptor() ([]byte, []int) {
	return fileDescriptor_81657e36c0b4b126, []int{4}
}

func (m *ReplyCollectiveList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReplyCollectiveList.Unmarshal(m, b)
}
func (m *ReplyCollectiveList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReplyCollectiveList.Marshal(b, m, deterministic)
}
func (m *ReplyCollectiveList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReplyCollectiveList.Merge(m, src)
}
func (m *ReplyCollectiveList) XXX_Size() int {
	return xxx_messageInfo_ReplyCollectiveList.Size(m)
}
func (m *ReplyCollectiveList) XXX_DiscardUnknown() {
	xxx_messageInfo_ReplyCollectiveList.DiscardUnknown(m)
}

var xxx_messageInfo_ReplyCollectiveList proto.InternalMessageInfo

func (m *ReplyCollectiveList) GetStatus() *ReplyStatus {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *ReplyCollectiveList) GetList() []*CollectiveInfo {
	if m != nil {
		return m.List
	}
	return nil
}

func init() {
	proto.RegisterType((*CollectiveInfo)(nil), "omo.msp.album.CollectiveInfo")
	proto.RegisterType((*ReqCollectiveAdd)(nil), "omo.msp.album.ReqCollectiveAdd")
	proto.RegisterType((*ReqCollectiveUpdate)(nil), "omo.msp.album.ReqCollectiveUpdate")
	proto.RegisterType((*ReplyCollectiveInfo)(nil), "omo.msp.album.ReplyCollectiveInfo")
	proto.RegisterType((*ReplyCollectiveList)(nil), "omo.msp.album.ReplyCollectiveList")
}

func init() {
	proto.RegisterFile("proto/album/collective.proto", fileDescriptor_81657e36c0b4b126)
}

var fileDescriptor_81657e36c0b4b126 = []byte{
	// 682 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x55, 0x4f, 0x4f, 0xdb, 0x4a,
	0x10, 0xc7, 0x71, 0x12, 0x60, 0x42, 0x02, 0xec, 0x7b, 0x0f, 0xad, 0xf2, 0xe0, 0x3d, 0xcb, 0xa7,
	0x9c, 0x82, 0x9a, 0x1e, 0x7a, 0x0e, 0xb4, 0x44, 0x20, 0x2a, 0x24, 0x47, 0x5c, 0x7a, 0x33, 0xf6,
	0x42, 0x57, 0xb5, 0xbd, 0x66, 0x77, 0x9d, 0x8a, 0xaa, 0xd7, 0x7e, 0xac, 0x7e, 0x93, 0xde, 0xfa,
	0x45, 0xaa, 0x1d, 0x1b, 0x13, 0x07, 0x07, 0xd2, 0x72, 0xdb, 0xdf, 0xfc, 0xf9, 0xcd, 0xfc, 0x66,
	0x26, 0x31, 0xec, 0xa7, 0x52, 0x68, 0x71, 0xe8, 0x47, 0x57, 0x59, 0x7c, 0x18, 0x88, 0x28, 0x62,
	0x81, 0xe6, 0x33, 0x36, 0x44, 0x33, 0xe9, 0x8a, 0x58, 0x0c, 0x63, 0x95, 0x0e, 0xd1, 0xdf, 0xa7,
	0xd5, 0xe0, 0x38, 0x16, 0x49, 0x1e, 0xe8, 0xfe, 0xb4, 0xa1, 0x77, 0x5c, 0x66, 0x9f, 0x26, 0xd7,
	0x82, 0xec, 0x80, 0x9d, 0xf1, 0x90, 0x5a, 0x8e, 0x35, 0xd8, 0xf4, 0xcc, 0x93, 0xf4, 0xa0, 0xc1,
	0x43, 0xda, 0x70, 0xac, 0x41, 0xd3, 0x6b, 0xf0, 0x90, 0x50, 0x58, 0x0f, 0x24, 0xf3, 0x35, 0x0b,
	0xa9, 0xed, 0x58, 0x03, 0xdb, 0xbb, 0x87, 0xc6, 0x93, 0xa5, 0x21, 0x7a, 0x9a, 0xb9, 0xa7, 0x80,
	0x65, 0x8e, 0x90, 0xb4, 0x85, 0xcc, 0xf7, 0x90, 0xf4, 0x61, 0x43, 0xa4, 0x4c, 0xa2, 0xab, 0x8d,
	0xae, 0x12, 0x13, 0x02, 0xcd, 0xc4, 0x8f, 0x19, 0x5d, 0x47, 0x3b, 0xbe, 0xc9, 0x1e, 0xb4, 0x25,
	0x8b, 0x7d, 0xf9, 0x89, 0x6e, 0xa0, 0xb5, 0x40, 0xe4, 0x6f, 0x68, 0x05, 0x62, 0xc6, 0x24, 0xdd,
	0x44, 0x73, 0x0e, 0x8c, 0x55, 0x7c, 0x4e, 0x98, 0xa4, 0x90, 0x5b, 0x11, 0x18, 0x5e, 0xc5, 0xbf,
	0x30, 0xda, 0x41, 0x4d, 0xf8, 0x36, 0x91, 0x11, 0x8f, 0xb9, 0xa6, 0x5b, 0x8e, 0x35, 0xe8, 0x7a,
	0x39, 0xc0, 0x48, 0xed, 0x4b, 0xda, 0x45, 0x23, 0xbe, 0x4d, 0x07, 0x4a, 0xfb, 0x3a, 0x53, 0xb4,
	0x87, 0xd6, 0x02, 0x91, 0xff, 0x00, 0x52, 0x26, 0x63, 0xae, 0x14, 0x17, 0x09, 0xdd, 0x46, 0xdf,
	0x9c, 0xc5, 0x70, 0xe9, 0xbb, 0x94, 0xd1, 0x9d, 0x9c, 0xcb, 0xbc, 0xc9, 0x1b, 0xd8, 0x08, 0x33,
	0xe9, 0x6b, 0x93, 0xb1, 0xeb, 0x58, 0x83, 0xce, 0xe8, 0xdf, 0x61, 0x65, 0x79, 0xc3, 0xb7, 0x85,
	0xdb, 0x2c, 0xc7, 0x2b, 0x83, 0x4d, 0x13, 0xbe, 0x52, 0x4c, 0x2b, 0xfa, 0x8f, 0x63, 0x9b, 0x31,
	0xe4, 0x08, 0x8b, 0xf8, 0x37, 0x8a, 0xee, 0xa1, 0x15, 0xdf, 0xee, 0x77, 0x0b, 0x76, 0x3c, 0x76,
	0xfb, 0xb0, 0xe8, 0x71, 0x18, 0x96, 0xb3, 0xb5, 0x6a, 0x67, 0xdb, 0xa8, 0xcc, 0x76, 0x7e, 0x47,
	0xf6, 0xc2, 0x8e, 0xca, 0x09, 0x37, 0x17, 0x26, 0x8c, 0x5a, 0x5b, 0x4b, 0xb4, 0x76, 0x7e, 0x43,
	0xab, 0xfb, 0xcd, 0x82, 0xbf, 0x2a, 0xfd, 0x5f, 0xe2, 0x55, 0xd5, 0x9c, 0xea, 0xbd, 0xa8, 0x46,
	0xad, 0x28, 0xbb, 0xfe, 0x60, 0x9a, 0xf3, 0x07, 0x33, 0x2f, 0xb5, 0x55, 0x95, 0xea, 0x7e, 0x35,
	0x6d, 0xa4, 0xd1, 0xdd, 0xc2, 0x2f, 0x66, 0x54, 0xde, 0x83, 0x85, 0xaa, 0xfa, 0x0b, 0xaa, 0x30,
	0x67, 0x8a, 0x11, 0xe5, 0xad, 0xbc, 0x82, 0x26, 0x4f, 0xae, 0x05, 0x36, 0xda, 0x19, 0x1d, 0x2c,
	0x64, 0x54, 0x0b, 0x78, 0x18, 0x5a, 0x53, 0xfd, 0x9c, 0x2b, 0xfd, 0xa7, 0xd5, 0x23, 0xae, 0x34,
	0x6d, 0x38, 0xf6, 0x0a, 0xd5, 0x4d, 0xe8, 0xe8, 0x47, 0x1b, 0x76, 0x1f, 0x1c, 0x53, 0x26, 0x67,
	0x3c, 0x60, 0xe4, 0x02, 0xda, 0xe3, 0x30, 0xbc, 0x48, 0x18, 0xf9, 0xff, 0x51, 0xd9, 0xea, 0xbd,
	0xf5, 0xdd, 0xba, 0xbe, 0xaa, 0xa5, 0xdc, 0x35, 0x72, 0x0e, 0x90, 0x2f, 0xf7, 0xc8, 0x57, 0x8c,
	0xb8, 0x4f, 0x91, 0xe6, 0x71, 0x7d, 0x5a, 0xc7, 0x5b, 0xb0, 0x1d, 0xc3, 0xa6, 0xc7, 0x62, 0x31,
	0x63, 0xa6, 0xc3, 0xc7, 0x83, 0xb9, 0xcd, 0x98, 0xd2, 0x26, 0xf4, 0x49, 0x92, 0x33, 0x68, 0x4f,
	0x98, 0x7e, 0x8e, 0x61, 0x35, 0x79, 0x67, 0xd0, 0x9e, 0x32, 0x5f, 0x06, 0x1f, 0x5f, 0xc2, 0x65,
	0xd6, 0xee, 0xae, 0x91, 0x4b, 0xd8, 0x9e, 0x30, 0x6d, 0xc0, 0xd1, 0xdd, 0x09, 0x8f, 0x34, 0x93,
	0x64, 0xbf, 0x9e, 0x34, 0xf7, 0xae, 0x48, 0xfb, 0x1e, 0xb6, 0x26, 0x4c, 0x9b, 0x83, 0xe1, 0x4a,
	0xf3, 0xe0, 0x19, 0xce, 0x83, 0x65, 0xd7, 0x86, 0xc9, 0xa8, 0xb8, 0x57, 0x2c, 0xf4, 0x99, 0x26,
	0x57, 0x58, 0xe7, 0x29, 0x6c, 0xe5, 0x51, 0xf9, 0x39, 0x93, 0x83, 0x65, 0x33, 0xd4, 0x27, 0x91,
	0x7f, 0xf3, 0x24, 0xd5, 0x3b, 0xe8, 0x8c, 0xd3, 0x94, 0x25, 0xe1, 0xd8, 0xfc, 0x6d, 0x2e, 0xdb,
	0x86, 0x19, 0x49, 0x3d, 0x4d, 0x31, 0xac, 0x09, 0x74, 0xa7, 0xd9, 0x95, 0x96, 0x7e, 0xa0, 0x5f,
	0x44, 0x74, 0xd4, 0xfd, 0xd0, 0x99, 0xfb, 0x48, 0x5f, 0xb5, 0x11, 0xbc, 0xfe, 0x15, 0x00, 0x00,
	0xff, 0xff, 0x59, 0xc0, 0x45, 0xa1, 0xe7, 0x07, 0x00, 0x00,
}
