// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/album/page.proto

package album

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type PageInfo struct {
	Uid                  string         `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Id                   uint64         `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	Created              int64          `protobuf:"varint,3,opt,name=created,proto3" json:"created,omitempty"`
	Updated              int64          `protobuf:"varint,4,opt,name=updated,proto3" json:"updated,omitempty"`
	Creator              string         `protobuf:"bytes,5,opt,name=creator,proto3" json:"creator,omitempty"`
	Operator             string         `protobuf:"bytes,6,opt,name=operator,proto3" json:"operator,omitempty"`
	Name                 string         `protobuf:"bytes,7,opt,name=name,proto3" json:"name,omitempty"`
	Remark               string         `protobuf:"bytes,8,opt,name=remark,proto3" json:"remark,omitempty"`
	Owner                string         `protobuf:"bytes,9,opt,name=owner,proto3" json:"owner,omitempty"`
	Composition          string         `protobuf:"bytes,10,opt,name=composition,proto3" json:"composition,omitempty"`
	Type                 uint32         `protobuf:"varint,11,opt,name=type,proto3" json:"type,omitempty"`
	Lifecycle            uint32         `protobuf:"varint,12,opt,name=lifecycle,proto3" json:"lifecycle,omitempty"`
	Tags                 []string       `protobuf:"bytes,21,rep,name=tags,proto3" json:"tags,omitempty"`
	Contents             []*PageContent `protobuf:"bytes,31,rep,name=contents,proto3" json:"contents,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *PageInfo) Reset()         { *m = PageInfo{} }
func (m *PageInfo) String() string { return proto.CompactTextString(m) }
func (*PageInfo) ProtoMessage()    {}
func (*PageInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_6de73a99ec413d54, []int{0}
}

func (m *PageInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PageInfo.Unmarshal(m, b)
}
func (m *PageInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PageInfo.Marshal(b, m, deterministic)
}
func (m *PageInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PageInfo.Merge(m, src)
}
func (m *PageInfo) XXX_Size() int {
	return xxx_messageInfo_PageInfo.Size(m)
}
func (m *PageInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_PageInfo.DiscardUnknown(m)
}

var xxx_messageInfo_PageInfo proto.InternalMessageInfo

func (m *PageInfo) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *PageInfo) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *PageInfo) GetCreated() int64 {
	if m != nil {
		return m.Created
	}
	return 0
}

func (m *PageInfo) GetUpdated() int64 {
	if m != nil {
		return m.Updated
	}
	return 0
}

func (m *PageInfo) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *PageInfo) GetOperator() string {
	if m != nil {
		return m.Operator
	}
	return ""
}

func (m *PageInfo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *PageInfo) GetRemark() string {
	if m != nil {
		return m.Remark
	}
	return ""
}

func (m *PageInfo) GetOwner() string {
	if m != nil {
		return m.Owner
	}
	return ""
}

func (m *PageInfo) GetComposition() string {
	if m != nil {
		return m.Composition
	}
	return ""
}

func (m *PageInfo) GetType() uint32 {
	if m != nil {
		return m.Type
	}
	return 0
}

func (m *PageInfo) GetLifecycle() uint32 {
	if m != nil {
		return m.Lifecycle
	}
	return 0
}

func (m *PageInfo) GetTags() []string {
	if m != nil {
		return m.Tags
	}
	return nil
}

func (m *PageInfo) GetContents() []*PageContent {
	if m != nil {
		return m.Contents
	}
	return nil
}

type PageContent struct {
	Type                 uint32   `protobuf:"varint,1,opt,name=type,proto3" json:"type,omitempty"`
	Slot                 uint32   `protobuf:"varint,2,opt,name=slot,proto3" json:"slot,omitempty"`
	Way                  uint32   `protobuf:"varint,3,opt,name=way,proto3" json:"way,omitempty"`
	Interval             uint32   `protobuf:"varint,4,opt,name=interval,proto3" json:"interval,omitempty"`
	List                 []string `protobuf:"bytes,10,rep,name=list,proto3" json:"list,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PageContent) Reset()         { *m = PageContent{} }
func (m *PageContent) String() string { return proto.CompactTextString(m) }
func (*PageContent) ProtoMessage()    {}
func (*PageContent) Descriptor() ([]byte, []int) {
	return fileDescriptor_6de73a99ec413d54, []int{1}
}

func (m *PageContent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PageContent.Unmarshal(m, b)
}
func (m *PageContent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PageContent.Marshal(b, m, deterministic)
}
func (m *PageContent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PageContent.Merge(m, src)
}
func (m *PageContent) XXX_Size() int {
	return xxx_messageInfo_PageContent.Size(m)
}
func (m *PageContent) XXX_DiscardUnknown() {
	xxx_messageInfo_PageContent.DiscardUnknown(m)
}

var xxx_messageInfo_PageContent proto.InternalMessageInfo

func (m *PageContent) GetType() uint32 {
	if m != nil {
		return m.Type
	}
	return 0
}

func (m *PageContent) GetSlot() uint32 {
	if m != nil {
		return m.Slot
	}
	return 0
}

func (m *PageContent) GetWay() uint32 {
	if m != nil {
		return m.Way
	}
	return 0
}

func (m *PageContent) GetInterval() uint32 {
	if m != nil {
		return m.Interval
	}
	return 0
}

func (m *PageContent) GetList() []string {
	if m != nil {
		return m.List
	}
	return nil
}

type ReqPageAdd struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Remark               string   `protobuf:"bytes,2,opt,name=remark,proto3" json:"remark,omitempty"`
	Operator             string   `protobuf:"bytes,3,opt,name=operator,proto3" json:"operator,omitempty"`
	Owner                string   `protobuf:"bytes,4,opt,name=owner,proto3" json:"owner,omitempty"`
	Type                 uint32   `protobuf:"varint,5,opt,name=type,proto3" json:"type,omitempty"`
	Composition          string   `protobuf:"bytes,6,opt,name=composition,proto3" json:"composition,omitempty"`
	Lifecycle            uint32   `protobuf:"varint,7,opt,name=lifecycle,proto3" json:"lifecycle,omitempty"`
	Tags                 []string `protobuf:"bytes,11,rep,name=tags,proto3" json:"tags,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqPageAdd) Reset()         { *m = ReqPageAdd{} }
func (m *ReqPageAdd) String() string { return proto.CompactTextString(m) }
func (*ReqPageAdd) ProtoMessage()    {}
func (*ReqPageAdd) Descriptor() ([]byte, []int) {
	return fileDescriptor_6de73a99ec413d54, []int{2}
}

func (m *ReqPageAdd) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqPageAdd.Unmarshal(m, b)
}
func (m *ReqPageAdd) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqPageAdd.Marshal(b, m, deterministic)
}
func (m *ReqPageAdd) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqPageAdd.Merge(m, src)
}
func (m *ReqPageAdd) XXX_Size() int {
	return xxx_messageInfo_ReqPageAdd.Size(m)
}
func (m *ReqPageAdd) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqPageAdd.DiscardUnknown(m)
}

var xxx_messageInfo_ReqPageAdd proto.InternalMessageInfo

func (m *ReqPageAdd) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ReqPageAdd) GetRemark() string {
	if m != nil {
		return m.Remark
	}
	return ""
}

func (m *ReqPageAdd) GetOperator() string {
	if m != nil {
		return m.Operator
	}
	return ""
}

func (m *ReqPageAdd) GetOwner() string {
	if m != nil {
		return m.Owner
	}
	return ""
}

func (m *ReqPageAdd) GetType() uint32 {
	if m != nil {
		return m.Type
	}
	return 0
}

func (m *ReqPageAdd) GetComposition() string {
	if m != nil {
		return m.Composition
	}
	return ""
}

func (m *ReqPageAdd) GetLifecycle() uint32 {
	if m != nil {
		return m.Lifecycle
	}
	return 0
}

func (m *ReqPageAdd) GetTags() []string {
	if m != nil {
		return m.Tags
	}
	return nil
}

type ReqPageUpdate struct {
	Uid                  string   `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Remark               string   `protobuf:"bytes,3,opt,name=remark,proto3" json:"remark,omitempty"`
	Operator             string   `protobuf:"bytes,4,opt,name=operator,proto3" json:"operator,omitempty"`
	Lifecycle            uint32   `protobuf:"varint,5,opt,name=lifecycle,proto3" json:"lifecycle,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqPageUpdate) Reset()         { *m = ReqPageUpdate{} }
func (m *ReqPageUpdate) String() string { return proto.CompactTextString(m) }
func (*ReqPageUpdate) ProtoMessage()    {}
func (*ReqPageUpdate) Descriptor() ([]byte, []int) {
	return fileDescriptor_6de73a99ec413d54, []int{3}
}

func (m *ReqPageUpdate) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqPageUpdate.Unmarshal(m, b)
}
func (m *ReqPageUpdate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqPageUpdate.Marshal(b, m, deterministic)
}
func (m *ReqPageUpdate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqPageUpdate.Merge(m, src)
}
func (m *ReqPageUpdate) XXX_Size() int {
	return xxx_messageInfo_ReqPageUpdate.Size(m)
}
func (m *ReqPageUpdate) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqPageUpdate.DiscardUnknown(m)
}

var xxx_messageInfo_ReqPageUpdate proto.InternalMessageInfo

func (m *ReqPageUpdate) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *ReqPageUpdate) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ReqPageUpdate) GetRemark() string {
	if m != nil {
		return m.Remark
	}
	return ""
}

func (m *ReqPageUpdate) GetOperator() string {
	if m != nil {
		return m.Operator
	}
	return ""
}

func (m *ReqPageUpdate) GetLifecycle() uint32 {
	if m != nil {
		return m.Lifecycle
	}
	return 0
}

type ReqPageContent struct {
	Uid                  string   `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Slot                 uint32   `protobuf:"varint,2,opt,name=slot,proto3" json:"slot,omitempty"`
	Way                  uint32   `protobuf:"varint,3,opt,name=way,proto3" json:"way,omitempty"`
	Operator             string   `protobuf:"bytes,4,opt,name=operator,proto3" json:"operator,omitempty"`
	Type                 uint32   `protobuf:"varint,5,opt,name=type,proto3" json:"type,omitempty"`
	Assets               []string `protobuf:"bytes,11,rep,name=assets,proto3" json:"assets,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqPageContent) Reset()         { *m = ReqPageContent{} }
func (m *ReqPageContent) String() string { return proto.CompactTextString(m) }
func (*ReqPageContent) ProtoMessage()    {}
func (*ReqPageContent) Descriptor() ([]byte, []int) {
	return fileDescriptor_6de73a99ec413d54, []int{4}
}

func (m *ReqPageContent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqPageContent.Unmarshal(m, b)
}
func (m *ReqPageContent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqPageContent.Marshal(b, m, deterministic)
}
func (m *ReqPageContent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqPageContent.Merge(m, src)
}
func (m *ReqPageContent) XXX_Size() int {
	return xxx_messageInfo_ReqPageContent.Size(m)
}
func (m *ReqPageContent) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqPageContent.DiscardUnknown(m)
}

var xxx_messageInfo_ReqPageContent proto.InternalMessageInfo

func (m *ReqPageContent) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *ReqPageContent) GetSlot() uint32 {
	if m != nil {
		return m.Slot
	}
	return 0
}

func (m *ReqPageContent) GetWay() uint32 {
	if m != nil {
		return m.Way
	}
	return 0
}

func (m *ReqPageContent) GetOperator() string {
	if m != nil {
		return m.Operator
	}
	return ""
}

func (m *ReqPageContent) GetType() uint32 {
	if m != nil {
		return m.Type
	}
	return 0
}

func (m *ReqPageContent) GetAssets() []string {
	if m != nil {
		return m.Assets
	}
	return nil
}

type ReplyPageContent struct {
	Status               *ReplyStatus   `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Uid                  string         `protobuf:"bytes,2,opt,name=uid,proto3" json:"uid,omitempty"`
	List                 []*PageContent `protobuf:"bytes,11,rep,name=list,proto3" json:"list,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *ReplyPageContent) Reset()         { *m = ReplyPageContent{} }
func (m *ReplyPageContent) String() string { return proto.CompactTextString(m) }
func (*ReplyPageContent) ProtoMessage()    {}
func (*ReplyPageContent) Descriptor() ([]byte, []int) {
	return fileDescriptor_6de73a99ec413d54, []int{5}
}

func (m *ReplyPageContent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReplyPageContent.Unmarshal(m, b)
}
func (m *ReplyPageContent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReplyPageContent.Marshal(b, m, deterministic)
}
func (m *ReplyPageContent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReplyPageContent.Merge(m, src)
}
func (m *ReplyPageContent) XXX_Size() int {
	return xxx_messageInfo_ReplyPageContent.Size(m)
}
func (m *ReplyPageContent) XXX_DiscardUnknown() {
	xxx_messageInfo_ReplyPageContent.DiscardUnknown(m)
}

var xxx_messageInfo_ReplyPageContent proto.InternalMessageInfo

func (m *ReplyPageContent) GetStatus() *ReplyStatus {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *ReplyPageContent) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *ReplyPageContent) GetList() []*PageContent {
	if m != nil {
		return m.List
	}
	return nil
}

type ReqPageAppend struct {
	Uid                  string         `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Operator             string         `protobuf:"bytes,2,opt,name=operator,proto3" json:"operator,omitempty"`
	Contents             []*PageContent `protobuf:"bytes,11,rep,name=contents,proto3" json:"contents,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *ReqPageAppend) Reset()         { *m = ReqPageAppend{} }
func (m *ReqPageAppend) String() string { return proto.CompactTextString(m) }
func (*ReqPageAppend) ProtoMessage()    {}
func (*ReqPageAppend) Descriptor() ([]byte, []int) {
	return fileDescriptor_6de73a99ec413d54, []int{6}
}

func (m *ReqPageAppend) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqPageAppend.Unmarshal(m, b)
}
func (m *ReqPageAppend) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqPageAppend.Marshal(b, m, deterministic)
}
func (m *ReqPageAppend) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqPageAppend.Merge(m, src)
}
func (m *ReqPageAppend) XXX_Size() int {
	return xxx_messageInfo_ReqPageAppend.Size(m)
}
func (m *ReqPageAppend) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqPageAppend.DiscardUnknown(m)
}

var xxx_messageInfo_ReqPageAppend proto.InternalMessageInfo

func (m *ReqPageAppend) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *ReqPageAppend) GetOperator() string {
	if m != nil {
		return m.Operator
	}
	return ""
}

func (m *ReqPageAppend) GetContents() []*PageContent {
	if m != nil {
		return m.Contents
	}
	return nil
}

type ReplyPageContents struct {
	Status               *ReplyStatus   `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Uid                  string         `protobuf:"bytes,2,opt,name=uid,proto3" json:"uid,omitempty"`
	List                 []*PageContent `protobuf:"bytes,11,rep,name=list,proto3" json:"list,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *ReplyPageContents) Reset()         { *m = ReplyPageContents{} }
func (m *ReplyPageContents) String() string { return proto.CompactTextString(m) }
func (*ReplyPageContents) ProtoMessage()    {}
func (*ReplyPageContents) Descriptor() ([]byte, []int) {
	return fileDescriptor_6de73a99ec413d54, []int{7}
}

func (m *ReplyPageContents) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReplyPageContents.Unmarshal(m, b)
}
func (m *ReplyPageContents) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReplyPageContents.Marshal(b, m, deterministic)
}
func (m *ReplyPageContents) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReplyPageContents.Merge(m, src)
}
func (m *ReplyPageContents) XXX_Size() int {
	return xxx_messageInfo_ReplyPageContents.Size(m)
}
func (m *ReplyPageContents) XXX_DiscardUnknown() {
	xxx_messageInfo_ReplyPageContents.DiscardUnknown(m)
}

var xxx_messageInfo_ReplyPageContents proto.InternalMessageInfo

func (m *ReplyPageContents) GetStatus() *ReplyStatus {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *ReplyPageContents) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *ReplyPageContents) GetList() []*PageContent {
	if m != nil {
		return m.List
	}
	return nil
}

type ReplyPageInfo struct {
	Status               *ReplyStatus `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Info                 *PageInfo    `protobuf:"bytes,2,opt,name=info,proto3" json:"info,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *ReplyPageInfo) Reset()         { *m = ReplyPageInfo{} }
func (m *ReplyPageInfo) String() string { return proto.CompactTextString(m) }
func (*ReplyPageInfo) ProtoMessage()    {}
func (*ReplyPageInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_6de73a99ec413d54, []int{8}
}

func (m *ReplyPageInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReplyPageInfo.Unmarshal(m, b)
}
func (m *ReplyPageInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReplyPageInfo.Marshal(b, m, deterministic)
}
func (m *ReplyPageInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReplyPageInfo.Merge(m, src)
}
func (m *ReplyPageInfo) XXX_Size() int {
	return xxx_messageInfo_ReplyPageInfo.Size(m)
}
func (m *ReplyPageInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_ReplyPageInfo.DiscardUnknown(m)
}

var xxx_messageInfo_ReplyPageInfo proto.InternalMessageInfo

func (m *ReplyPageInfo) GetStatus() *ReplyStatus {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *ReplyPageInfo) GetInfo() *PageInfo {
	if m != nil {
		return m.Info
	}
	return nil
}

type ReplyPageList struct {
	Status               *ReplyStatus `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	List                 []*PageInfo  `protobuf:"bytes,2,rep,name=list,proto3" json:"list,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *ReplyPageList) Reset()         { *m = ReplyPageList{} }
func (m *ReplyPageList) String() string { return proto.CompactTextString(m) }
func (*ReplyPageList) ProtoMessage()    {}
func (*ReplyPageList) Descriptor() ([]byte, []int) {
	return fileDescriptor_6de73a99ec413d54, []int{9}
}

func (m *ReplyPageList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReplyPageList.Unmarshal(m, b)
}
func (m *ReplyPageList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReplyPageList.Marshal(b, m, deterministic)
}
func (m *ReplyPageList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReplyPageList.Merge(m, src)
}
func (m *ReplyPageList) XXX_Size() int {
	return xxx_messageInfo_ReplyPageList.Size(m)
}
func (m *ReplyPageList) XXX_DiscardUnknown() {
	xxx_messageInfo_ReplyPageList.DiscardUnknown(m)
}

var xxx_messageInfo_ReplyPageList proto.InternalMessageInfo

func (m *ReplyPageList) GetStatus() *ReplyStatus {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *ReplyPageList) GetList() []*PageInfo {
	if m != nil {
		return m.List
	}
	return nil
}

func init() {
	proto.RegisterType((*PageInfo)(nil), "omo.msp.album.PageInfo")
	proto.RegisterType((*PageContent)(nil), "omo.msp.album.PageContent")
	proto.RegisterType((*ReqPageAdd)(nil), "omo.msp.album.ReqPageAdd")
	proto.RegisterType((*ReqPageUpdate)(nil), "omo.msp.album.ReqPageUpdate")
	proto.RegisterType((*ReqPageContent)(nil), "omo.msp.album.ReqPageContent")
	proto.RegisterType((*ReplyPageContent)(nil), "omo.msp.album.ReplyPageContent")
	proto.RegisterType((*ReqPageAppend)(nil), "omo.msp.album.ReqPageAppend")
	proto.RegisterType((*ReplyPageContents)(nil), "omo.msp.album.ReplyPageContents")
	proto.RegisterType((*ReplyPageInfo)(nil), "omo.msp.album.ReplyPageInfo")
	proto.RegisterType((*ReplyPageList)(nil), "omo.msp.album.ReplyPageList")
}

func init() {
	proto.RegisterFile("proto/album/page.proto", fileDescriptor_6de73a99ec413d54)
}

var fileDescriptor_6de73a99ec413d54 = []byte{
	// 754 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xc4, 0x56, 0xcd, 0x6e, 0xdb, 0x46,
	0x10, 0x36, 0x29, 0x89, 0x96, 0x86, 0x96, 0xe1, 0x2e, 0x5a, 0x77, 0x2b, 0xd8, 0x28, 0xc1, 0x93,
	0x80, 0x02, 0x32, 0xa0, 0x02, 0xbd, 0xfb, 0x07, 0x36, 0x0c, 0xb4, 0x70, 0x41, 0xa1, 0x97, 0xde,
	0x68, 0x72, 0xec, 0x10, 0x21, 0xb9, 0x34, 0x77, 0x65, 0x43, 0x4f, 0x90, 0xe4, 0x96, 0x07, 0xc8,
	0x53, 0xe5, 0x69, 0x72, 0x0c, 0x76, 0xf8, 0x63, 0x4a, 0xa2, 0x22, 0xc7, 0x97, 0xdc, 0x76, 0x76,
	0x86, 0xb3, 0xdf, 0xcf, 0xec, 0x82, 0x70, 0x98, 0xe5, 0x42, 0x89, 0x13, 0x3f, 0xbe, 0x9d, 0x27,
	0x27, 0x99, 0x7f, 0x8f, 0x13, 0xda, 0x60, 0x43, 0x91, 0x88, 0x49, 0x22, 0xb3, 0x09, 0x65, 0x46,
	0xbc, 0x59, 0x16, 0x88, 0x24, 0x11, 0x69, 0x51, 0xe8, 0x7e, 0x31, 0xa1, 0xff, 0xaf, 0x7f, 0x8f,
	0xd7, 0xe9, 0x9d, 0x60, 0x07, 0xd0, 0x99, 0x47, 0x21, 0x37, 0x1c, 0x63, 0x3c, 0xf0, 0xf4, 0x92,
	0xed, 0x83, 0x19, 0x85, 0xdc, 0x74, 0x8c, 0x71, 0xd7, 0x33, 0xa3, 0x90, 0x71, 0xd8, 0x0d, 0x72,
	0xf4, 0x15, 0x86, 0xbc, 0xe3, 0x18, 0xe3, 0x8e, 0x57, 0x85, 0x3a, 0x33, 0xcf, 0x42, 0xca, 0x74,
	0x8b, 0x4c, 0x19, 0xd6, 0xdf, 0x88, 0x9c, 0xf7, 0xa8, 0x73, 0x15, 0xb2, 0x11, 0xf4, 0x45, 0x86,
	0x39, 0xa5, 0x2c, 0x4a, 0xd5, 0x31, 0x63, 0xd0, 0x4d, 0xfd, 0x04, 0xf9, 0x2e, 0xed, 0xd3, 0x9a,
	0x1d, 0x82, 0x95, 0x63, 0xe2, 0xe7, 0x6f, 0x79, 0x9f, 0x76, 0xcb, 0x88, 0xfd, 0x0c, 0x3d, 0xf1,
	0x94, 0x62, 0xce, 0x07, 0xb4, 0x5d, 0x04, 0xcc, 0x01, 0x3b, 0x10, 0x49, 0x26, 0x64, 0xa4, 0x22,
	0x91, 0x72, 0xa0, 0x5c, 0x73, 0x4b, 0x9f, 0xa1, 0x16, 0x19, 0x72, 0xdb, 0x31, 0xc6, 0x43, 0x8f,
	0xd6, 0xec, 0x08, 0x06, 0x71, 0x74, 0x87, 0xc1, 0x22, 0x88, 0x91, 0xef, 0x51, 0xe2, 0x79, 0x83,
	0xbe, 0xf0, 0xef, 0x25, 0xff, 0xc5, 0xe9, 0x68, 0x54, 0x7a, 0xcd, 0xfe, 0x82, 0x7e, 0x20, 0x52,
	0x85, 0xa9, 0x92, 0xfc, 0x77, 0xa7, 0x33, 0xb6, 0xa7, 0xa3, 0xc9, 0x92, 0xfc, 0x13, 0x2d, 0xf0,
	0x79, 0x51, 0xe2, 0xd5, 0xb5, 0xee, 0x13, 0xd8, 0x8d, 0x44, 0x0d, 0xc6, 0x68, 0x80, 0x61, 0xd0,
	0x95, 0xb1, 0x50, 0x64, 0xc0, 0xd0, 0xa3, 0xb5, 0x36, 0xe9, 0xc9, 0x5f, 0x90, 0xfc, 0x43, 0x4f,
	0x2f, 0xb5, 0x8c, 0x51, 0xaa, 0x30, 0x7f, 0xf4, 0x63, 0xd2, 0x7e, 0xe8, 0xd5, 0xb1, 0xee, 0x10,
	0x47, 0x52, 0x71, 0x28, 0x00, 0xeb, 0xb5, 0xfb, 0xd9, 0x00, 0xf0, 0xf0, 0x41, 0x1f, 0x7e, 0x1a,
	0x86, 0xb5, 0xd2, 0x46, 0xab, 0xd2, 0xe6, 0x92, 0xd2, 0x4d, 0xc7, 0x3a, 0x2b, 0x8e, 0xd5, 0x2e,
	0x74, 0x9b, 0x2e, 0x54, 0xb4, 0x7a, 0x0d, 0x5a, 0x2b, 0xce, 0x58, 0xeb, 0xce, 0x2c, 0xb9, 0xb0,
	0xbb, 0xc9, 0x05, 0xfb, 0xd9, 0x05, 0xf7, 0x9d, 0x01, 0xc3, 0x92, 0xd4, 0x7f, 0x34, 0x78, 0x2d,
	0xd3, 0x5c, 0x31, 0x35, 0x5b, 0x99, 0x76, 0x36, 0x32, 0xed, 0xae, 0x30, 0x5d, 0x42, 0xd7, 0x5b,
	0x41, 0xe7, 0x7e, 0x34, 0x60, 0xbf, 0x44, 0x52, 0x79, 0xdb, 0x0a, 0xe5, 0x65, 0xce, 0x6e, 0x04,
	0xd1, 0x26, 0xec, 0x21, 0x58, 0xbe, 0x94, 0xa8, 0x2a, 0x69, 0xca, 0xc8, 0x7d, 0x6f, 0xc0, 0x81,
	0x87, 0x59, 0xbc, 0x68, 0x82, 0x9a, 0x82, 0x25, 0x95, 0xaf, 0xe6, 0x92, 0x70, 0xad, 0x4f, 0x2d,
	0x7d, 0x30, 0xa3, 0x0a, 0xaf, 0xac, 0xac, 0x88, 0x98, 0xcf, 0x44, 0x26, 0xe5, 0x80, 0xd9, 0x5b,
	0x27, 0xbf, 0x18, 0xbe, 0x79, 0x6d, 0xd3, 0x69, 0x96, 0x61, 0x1a, 0xb6, 0x68, 0xd3, 0x64, 0x6d,
	0xae, 0xb0, 0x6e, 0x5e, 0x36, 0xfb, 0x3b, 0x2e, 0xdb, 0x07, 0x03, 0x7e, 0x5a, 0x55, 0x40, 0xfe,
	0x20, 0x09, 0x32, 0x2d, 0x41, 0x09, 0x85, 0xde, 0xdd, 0xd7, 0xc0, 0xf8, 0x03, 0xba, 0x51, 0x7a,
	0x27, 0x08, 0x87, 0x3d, 0xfd, 0xb5, 0xe5, 0x50, 0xdd, 0xda, 0xa3, 0xa2, 0xa5, 0x13, 0xff, 0x8e,
	0xa4, 0x7a, 0xed, 0x89, 0x44, 0xd3, 0x24, 0x9a, 0x9b, 0x4f, 0xd4, 0x45, 0xd3, 0x4f, 0xbd, 0xe2,
	0x75, 0x9b, 0x61, 0xfe, 0x18, 0x05, 0xc8, 0xce, 0xc1, 0x3a, 0x0d, 0xc3, 0x9b, 0x14, 0xd9, 0x6f,
	0x6b, 0x47, 0x55, 0x2f, 0xd1, 0xe8, 0xa8, 0x0d, 0x45, 0xd5, 0xd8, 0xdd, 0x61, 0x97, 0x00, 0xc5,
	0xdd, 0x3e, 0xf3, 0x25, 0xb2, 0xa3, 0xf6, 0x46, 0x45, 0xc5, 0x88, 0xb7, 0xf5, 0x2a, 0xfb, 0x9c,
	0xc3, 0xc0, 0xc3, 0x44, 0x3c, 0xa2, 0xc6, 0xb3, 0x4e, 0xfd, 0x61, 0x8e, 0x52, 0xe9, 0xd2, 0x6f,
	0x36, 0xb9, 0x00, 0xeb, 0x0a, 0xd5, 0xb6, 0x0e, 0xdb, 0x28, 0x5d, 0x80, 0x35, 0x43, 0x3f, 0x0f,
	0xde, 0xbc, 0xae, 0x8b, 0x36, 0xd3, 0xdd, 0x61, 0xd7, 0x30, 0xb8, 0x42, 0xa5, 0x83, 0xb3, 0x45,
	0x9b, 0x2e, 0xba, 0xd1, 0x65, 0x14, 0x2b, 0xcc, 0xb7, 0xb6, 0xfa, 0x07, 0xf6, 0xae, 0x50, 0x69,
	0xeb, 0x23, 0xa9, 0xa2, 0x60, 0x4b, 0xb7, 0xe3, 0x4d, 0x73, 0x43, 0x1f, 0x13, 0xbf, 0x7e, 0x69,
	0xd9, 0x46, 0x60, 0x2f, 0x30, 0xec, 0x06, 0x60, 0x86, 0xaa, 0x7a, 0xb8, 0x8e, 0xdb, 0x8d, 0x2f,
	0xd3, 0x23, 0x67, 0x13, 0xc3, 0xea, 0xda, 0xbb, 0x3b, 0x67, 0xc3, 0xff, 0xed, 0xc6, 0x2f, 0xd1,
	0xad, 0x45, 0xc1, 0x9f, 0x5f, 0x03, 0x00, 0x00, 0xff, 0xff, 0xe0, 0xc5, 0xdc, 0xa0, 0x4f, 0x09,
	0x00, 0x00,
}
