// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/album/panorama.proto

package album

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type PanoramaInfo struct {
	Uid                  string   `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Id                   uint64   `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	Created              int64    `protobuf:"varint,3,opt,name=created,proto3" json:"created,omitempty"`
	Updated              int64    `protobuf:"varint,4,opt,name=updated,proto3" json:"updated,omitempty"`
	Creator              string   `protobuf:"bytes,5,opt,name=creator,proto3" json:"creator,omitempty"`
	Operator             string   `protobuf:"bytes,6,opt,name=operator,proto3" json:"operator,omitempty"`
	Name                 string   `protobuf:"bytes,7,opt,name=name,proto3" json:"name,omitempty"`
	Remark               string   `protobuf:"bytes,8,opt,name=remark,proto3" json:"remark,omitempty"`
	Content              string   `protobuf:"bytes,9,opt,name=content,proto3" json:"content,omitempty"`
	Owner                string   `protobuf:"bytes,10,opt,name=owner,proto3" json:"owner,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PanoramaInfo) Reset()         { *m = PanoramaInfo{} }
func (m *PanoramaInfo) String() string { return proto.CompactTextString(m) }
func (*PanoramaInfo) ProtoMessage()    {}
func (*PanoramaInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_3f53e632e67bb7bd, []int{0}
}

func (m *PanoramaInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PanoramaInfo.Unmarshal(m, b)
}
func (m *PanoramaInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PanoramaInfo.Marshal(b, m, deterministic)
}
func (m *PanoramaInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PanoramaInfo.Merge(m, src)
}
func (m *PanoramaInfo) XXX_Size() int {
	return xxx_messageInfo_PanoramaInfo.Size(m)
}
func (m *PanoramaInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_PanoramaInfo.DiscardUnknown(m)
}

var xxx_messageInfo_PanoramaInfo proto.InternalMessageInfo

func (m *PanoramaInfo) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *PanoramaInfo) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *PanoramaInfo) GetCreated() int64 {
	if m != nil {
		return m.Created
	}
	return 0
}

func (m *PanoramaInfo) GetUpdated() int64 {
	if m != nil {
		return m.Updated
	}
	return 0
}

func (m *PanoramaInfo) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *PanoramaInfo) GetOperator() string {
	if m != nil {
		return m.Operator
	}
	return ""
}

func (m *PanoramaInfo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *PanoramaInfo) GetRemark() string {
	if m != nil {
		return m.Remark
	}
	return ""
}

func (m *PanoramaInfo) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func (m *PanoramaInfo) GetOwner() string {
	if m != nil {
		return m.Owner
	}
	return ""
}

type ReqPanoramaAdd struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Remark               string   `protobuf:"bytes,2,opt,name=remark,proto3" json:"remark,omitempty"`
	Operator             string   `protobuf:"bytes,3,opt,name=operator,proto3" json:"operator,omitempty"`
	Content              string   `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`
	Owner                string   `protobuf:"bytes,5,opt,name=owner,proto3" json:"owner,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqPanoramaAdd) Reset()         { *m = ReqPanoramaAdd{} }
func (m *ReqPanoramaAdd) String() string { return proto.CompactTextString(m) }
func (*ReqPanoramaAdd) ProtoMessage()    {}
func (*ReqPanoramaAdd) Descriptor() ([]byte, []int) {
	return fileDescriptor_3f53e632e67bb7bd, []int{1}
}

func (m *ReqPanoramaAdd) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqPanoramaAdd.Unmarshal(m, b)
}
func (m *ReqPanoramaAdd) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqPanoramaAdd.Marshal(b, m, deterministic)
}
func (m *ReqPanoramaAdd) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqPanoramaAdd.Merge(m, src)
}
func (m *ReqPanoramaAdd) XXX_Size() int {
	return xxx_messageInfo_ReqPanoramaAdd.Size(m)
}
func (m *ReqPanoramaAdd) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqPanoramaAdd.DiscardUnknown(m)
}

var xxx_messageInfo_ReqPanoramaAdd proto.InternalMessageInfo

func (m *ReqPanoramaAdd) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ReqPanoramaAdd) GetRemark() string {
	if m != nil {
		return m.Remark
	}
	return ""
}

func (m *ReqPanoramaAdd) GetOperator() string {
	if m != nil {
		return m.Operator
	}
	return ""
}

func (m *ReqPanoramaAdd) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func (m *ReqPanoramaAdd) GetOwner() string {
	if m != nil {
		return m.Owner
	}
	return ""
}

type ReqPanoramaUpdate struct {
	Uid                  string   `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Remark               string   `protobuf:"bytes,3,opt,name=remark,proto3" json:"remark,omitempty"`
	Content              string   `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`
	Operator             string   `protobuf:"bytes,5,opt,name=operator,proto3" json:"operator,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqPanoramaUpdate) Reset()         { *m = ReqPanoramaUpdate{} }
func (m *ReqPanoramaUpdate) String() string { return proto.CompactTextString(m) }
func (*ReqPanoramaUpdate) ProtoMessage()    {}
func (*ReqPanoramaUpdate) Descriptor() ([]byte, []int) {
	return fileDescriptor_3f53e632e67bb7bd, []int{2}
}

func (m *ReqPanoramaUpdate) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqPanoramaUpdate.Unmarshal(m, b)
}
func (m *ReqPanoramaUpdate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqPanoramaUpdate.Marshal(b, m, deterministic)
}
func (m *ReqPanoramaUpdate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqPanoramaUpdate.Merge(m, src)
}
func (m *ReqPanoramaUpdate) XXX_Size() int {
	return xxx_messageInfo_ReqPanoramaUpdate.Size(m)
}
func (m *ReqPanoramaUpdate) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqPanoramaUpdate.DiscardUnknown(m)
}

var xxx_messageInfo_ReqPanoramaUpdate proto.InternalMessageInfo

func (m *ReqPanoramaUpdate) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *ReqPanoramaUpdate) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ReqPanoramaUpdate) GetRemark() string {
	if m != nil {
		return m.Remark
	}
	return ""
}

func (m *ReqPanoramaUpdate) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func (m *ReqPanoramaUpdate) GetOperator() string {
	if m != nil {
		return m.Operator
	}
	return ""
}

type ReplyPanoramaInfo struct {
	Status               *ReplyStatus  `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Info                 *PanoramaInfo `protobuf:"bytes,2,opt,name=info,proto3" json:"info,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *ReplyPanoramaInfo) Reset()         { *m = ReplyPanoramaInfo{} }
func (m *ReplyPanoramaInfo) String() string { return proto.CompactTextString(m) }
func (*ReplyPanoramaInfo) ProtoMessage()    {}
func (*ReplyPanoramaInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_3f53e632e67bb7bd, []int{3}
}

func (m *ReplyPanoramaInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReplyPanoramaInfo.Unmarshal(m, b)
}
func (m *ReplyPanoramaInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReplyPanoramaInfo.Marshal(b, m, deterministic)
}
func (m *ReplyPanoramaInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReplyPanoramaInfo.Merge(m, src)
}
func (m *ReplyPanoramaInfo) XXX_Size() int {
	return xxx_messageInfo_ReplyPanoramaInfo.Size(m)
}
func (m *ReplyPanoramaInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_ReplyPanoramaInfo.DiscardUnknown(m)
}

var xxx_messageInfo_ReplyPanoramaInfo proto.InternalMessageInfo

func (m *ReplyPanoramaInfo) GetStatus() *ReplyStatus {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *ReplyPanoramaInfo) GetInfo() *PanoramaInfo {
	if m != nil {
		return m.Info
	}
	return nil
}

type ReplyPanoramaList struct {
	Status               *ReplyStatus    `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	List                 []*PanoramaInfo `protobuf:"bytes,2,rep,name=list,proto3" json:"list,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *ReplyPanoramaList) Reset()         { *m = ReplyPanoramaList{} }
func (m *ReplyPanoramaList) String() string { return proto.CompactTextString(m) }
func (*ReplyPanoramaList) ProtoMessage()    {}
func (*ReplyPanoramaList) Descriptor() ([]byte, []int) {
	return fileDescriptor_3f53e632e67bb7bd, []int{4}
}

func (m *ReplyPanoramaList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReplyPanoramaList.Unmarshal(m, b)
}
func (m *ReplyPanoramaList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReplyPanoramaList.Marshal(b, m, deterministic)
}
func (m *ReplyPanoramaList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReplyPanoramaList.Merge(m, src)
}
func (m *ReplyPanoramaList) XXX_Size() int {
	return xxx_messageInfo_ReplyPanoramaList.Size(m)
}
func (m *ReplyPanoramaList) XXX_DiscardUnknown() {
	xxx_messageInfo_ReplyPanoramaList.DiscardUnknown(m)
}

var xxx_messageInfo_ReplyPanoramaList proto.InternalMessageInfo

func (m *ReplyPanoramaList) GetStatus() *ReplyStatus {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *ReplyPanoramaList) GetList() []*PanoramaInfo {
	if m != nil {
		return m.List
	}
	return nil
}

func init() {
	proto.RegisterType((*PanoramaInfo)(nil), "omo.msp.album.PanoramaInfo")
	proto.RegisterType((*ReqPanoramaAdd)(nil), "omo.msp.album.ReqPanoramaAdd")
	proto.RegisterType((*ReqPanoramaUpdate)(nil), "omo.msp.album.ReqPanoramaUpdate")
	proto.RegisterType((*ReplyPanoramaInfo)(nil), "omo.msp.album.ReplyPanoramaInfo")
	proto.RegisterType((*ReplyPanoramaList)(nil), "omo.msp.album.ReplyPanoramaList")
}

func init() {
	proto.RegisterFile("proto/album/panorama.proto", fileDescriptor_3f53e632e67bb7bd)
}

var fileDescriptor_3f53e632e67bb7bd = []byte{
	// 512 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x94, 0xcd, 0x6e, 0xd3, 0x40,
	0x10, 0xc7, 0xeb, 0x8f, 0xb8, 0xcd, 0xa4, 0x4d, 0x61, 0x85, 0xd0, 0xca, 0x50, 0xc9, 0xca, 0x29,
	0xa7, 0x44, 0x0a, 0x4f, 0xd0, 0x20, 0x91, 0xf2, 0x25, 0x90, 0x23, 0x2e, 0xdc, 0xb6, 0xf1, 0x54,
	0xac, 0x88, 0xbd, 0xee, 0x7a, 0x53, 0xe8, 0x13, 0xc0, 0xfb, 0x22, 0x71, 0x46, 0x1e, 0x3b, 0xd1,
	0x26, 0x71, 0x70, 0xd5, 0x5b, 0xe6, 0xeb, 0xff, 0xff, 0x79, 0x67, 0x14, 0x08, 0x73, 0xad, 0x8c,
	0x1a, 0x8b, 0xe5, 0xf5, 0x2a, 0x1d, 0xe7, 0x22, 0x53, 0x5a, 0xa4, 0x62, 0x44, 0x49, 0x76, 0xa6,
	0x52, 0x35, 0x4a, 0x8b, 0x7c, 0x44, 0xd5, 0x90, 0xdb, 0xad, 0x0b, 0x95, 0xa6, 0x2a, 0xab, 0x1a,
	0x07, 0x7f, 0x1d, 0x38, 0xfd, 0x5c, 0xcf, 0xbe, 0xcd, 0x6e, 0x14, 0x7b, 0x02, 0xde, 0x4a, 0x26,
	0xdc, 0x89, 0x9c, 0x61, 0x37, 0x2e, 0x7f, 0xb2, 0x3e, 0xb8, 0x32, 0xe1, 0x6e, 0xe4, 0x0c, 0xfd,
	0xd8, 0x95, 0x09, 0xe3, 0x70, 0xbc, 0xd0, 0x28, 0x0c, 0x26, 0xdc, 0x8b, 0x9c, 0xa1, 0x17, 0xaf,
	0xc3, 0xb2, 0xb2, 0xca, 0x13, 0xaa, 0xf8, 0x55, 0xa5, 0x0e, 0x37, 0x33, 0x4a, 0xf3, 0x0e, 0x29,
	0xaf, 0x43, 0x16, 0xc2, 0x89, 0xca, 0x51, 0x53, 0x29, 0xa0, 0xd2, 0x26, 0x66, 0x0c, 0xfc, 0x4c,
	0xa4, 0xc8, 0x8f, 0x29, 0x4f, 0xbf, 0xd9, 0x73, 0x08, 0x34, 0xa6, 0x42, 0x7f, 0xe7, 0x27, 0x94,
	0xad, 0x23, 0x72, 0x50, 0x99, 0xc1, 0xcc, 0xf0, 0x6e, 0xed, 0x50, 0x85, 0xec, 0x19, 0x74, 0xd4,
	0x8f, 0x0c, 0x35, 0x07, 0xca, 0x57, 0xc1, 0xe0, 0xb7, 0x03, 0xfd, 0x18, 0x6f, 0xd7, 0xdf, 0x7e,
	0x99, 0x24, 0x1b, 0x3b, 0xa7, 0xd1, 0xce, 0xdd, 0xb2, 0xb3, 0xb1, 0xbd, 0x1d, 0x6c, 0x0b, 0xc5,
	0x3f, 0x80, 0xd2, 0xb1, 0x51, 0x7e, 0x39, 0xf0, 0xd4, 0x42, 0xf9, 0x42, 0x6f, 0xd6, 0xb0, 0x88,
	0x35, 0x9f, 0xdb, 0xc8, 0xe7, 0x1d, 0x7a, 0x8e, 0x1d, 0x06, 0x9b, 0xbc, 0xb3, 0x4d, 0x3e, 0xf8,
	0x59, 0x82, 0xe4, 0xcb, 0xfb, 0xad, 0x8b, 0x98, 0x40, 0x50, 0x18, 0x61, 0x56, 0x05, 0xb1, 0xf4,
	0x26, 0xe1, 0x68, 0xeb, 0xb8, 0x46, 0x34, 0x31, 0xa7, 0x8e, 0xb8, 0xee, 0x64, 0x63, 0xf0, 0x65,
	0x76, 0xa3, 0x08, 0xb5, 0x37, 0x79, 0xb1, 0x33, 0x61, 0xcb, 0xc7, 0xd4, 0xb8, 0xe7, 0xfc, 0x41,
	0x16, 0xe6, 0xb1, 0xce, 0x4b, 0x59, 0x18, 0xee, 0x46, 0x5e, 0xab, 0x73, 0xd9, 0x38, 0xf9, 0xe3,
	0xc3, 0xf9, 0x3a, 0x3d, 0x47, 0x7d, 0x27, 0x17, 0xc8, 0xde, 0x43, 0x70, 0x99, 0x24, 0x9f, 0x32,
	0x64, 0x17, 0x7b, 0x96, 0xf6, 0xc9, 0x84, 0x51, 0x13, 0x91, 0x6d, 0x32, 0x38, 0x62, 0xef, 0x00,
	0xaa, 0x95, 0x4e, 0x45, 0x81, 0x2c, 0x3a, 0x2c, 0x58, 0x75, 0x85, 0xbc, 0x49, 0xb3, 0xd6, 0x7a,
	0x0d, 0xdd, 0x18, 0x53, 0x75, 0x87, 0x25, 0xdb, 0xfe, 0x73, 0xdc, 0xae, 0xb0, 0x30, 0x65, 0xeb,
	0x7f, 0x45, 0xae, 0x20, 0x98, 0xa1, 0x69, 0x53, 0x78, 0xc8, 0xa7, 0x5d, 0x41, 0x30, 0x47, 0xa1,
	0x17, 0xdf, 0x1e, 0xaf, 0x54, 0x2e, 0x7a, 0x70, 0xc4, 0xe6, 0x70, 0x3e, 0x43, 0x53, 0x06, 0xd3,
	0xfb, 0x37, 0x72, 0x69, 0x50, 0xb3, 0x97, 0xcd, 0x92, 0x55, 0xf5, 0x41, 0xa2, 0x1f, 0xe1, 0x74,
	0x86, 0xa6, 0x3c, 0x10, 0x59, 0x18, 0xb9, 0x68, 0x51, 0xbc, 0x38, 0x74, 0x5d, 0x34, 0x4c, 0x8b,
	0xec, 0xd7, 0x8b, 0x6c, 0x41, 0x6c, 0x5f, 0xe4, 0xf4, 0xec, 0x6b, 0xcf, 0xfa, 0x4f, 0xbe, 0x0e,
	0x28, 0x78, 0xf5, 0x2f, 0x00, 0x00, 0xff, 0xff, 0xe6, 0xbd, 0x95, 0x23, 0xd4, 0x05, 0x00, 0x00,
}
