// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/album/style.proto

package album

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type StyleInfo struct {
	Uid                  string           `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Id                   uint64           `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	Created              int64            `protobuf:"varint,3,opt,name=created,proto3" json:"created,omitempty"`
	Updated              int64            `protobuf:"varint,4,opt,name=updated,proto3" json:"updated,omitempty"`
	Creator              string           `protobuf:"bytes,5,opt,name=creator,proto3" json:"creator,omitempty"`
	Operator             string           `protobuf:"bytes,6,opt,name=operator,proto3" json:"operator,omitempty"`
	Name                 string           `protobuf:"bytes,7,opt,name=name,proto3" json:"name,omitempty"`
	Remark               string           `protobuf:"bytes,8,opt,name=remark,proto3" json:"remark,omitempty"`
	Type                 uint32           `protobuf:"varint,9,opt,name=type,proto3" json:"type,omitempty"`
	Cover                string           `protobuf:"bytes,10,opt,name=cover,proto3" json:"cover,omitempty"`
	Size                 uint32           `protobuf:"varint,11,opt,name=size,proto3" json:"size,omitempty"`
	Price                uint32           `protobuf:"varint,12,opt,name=price,proto3" json:"price,omitempty"`
	Tags                 []string         `protobuf:"bytes,13,rep,name=tags,proto3" json:"tags,omitempty"`
	Slots                []*PhotocopySlot `protobuf:"bytes,14,rep,name=slots,proto3" json:"slots,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *StyleInfo) Reset()         { *m = StyleInfo{} }
func (m *StyleInfo) String() string { return proto.CompactTextString(m) }
func (*StyleInfo) ProtoMessage()    {}
func (*StyleInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_c94d61fa26c563fe, []int{0}
}

func (m *StyleInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StyleInfo.Unmarshal(m, b)
}
func (m *StyleInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StyleInfo.Marshal(b, m, deterministic)
}
func (m *StyleInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StyleInfo.Merge(m, src)
}
func (m *StyleInfo) XXX_Size() int {
	return xxx_messageInfo_StyleInfo.Size(m)
}
func (m *StyleInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_StyleInfo.DiscardUnknown(m)
}

var xxx_messageInfo_StyleInfo proto.InternalMessageInfo

func (m *StyleInfo) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *StyleInfo) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *StyleInfo) GetCreated() int64 {
	if m != nil {
		return m.Created
	}
	return 0
}

func (m *StyleInfo) GetUpdated() int64 {
	if m != nil {
		return m.Updated
	}
	return 0
}

func (m *StyleInfo) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *StyleInfo) GetOperator() string {
	if m != nil {
		return m.Operator
	}
	return ""
}

func (m *StyleInfo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *StyleInfo) GetRemark() string {
	if m != nil {
		return m.Remark
	}
	return ""
}

func (m *StyleInfo) GetType() uint32 {
	if m != nil {
		return m.Type
	}
	return 0
}

func (m *StyleInfo) GetCover() string {
	if m != nil {
		return m.Cover
	}
	return ""
}

func (m *StyleInfo) GetSize() uint32 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *StyleInfo) GetPrice() uint32 {
	if m != nil {
		return m.Price
	}
	return 0
}

func (m *StyleInfo) GetTags() []string {
	if m != nil {
		return m.Tags
	}
	return nil
}

func (m *StyleInfo) GetSlots() []*PhotocopySlot {
	if m != nil {
		return m.Slots
	}
	return nil
}

type ReqStyleAdd struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Remark               string   `protobuf:"bytes,2,opt,name=remark,proto3" json:"remark,omitempty"`
	Operator             string   `protobuf:"bytes,3,opt,name=operator,proto3" json:"operator,omitempty"`
	Type                 uint32   `protobuf:"varint,4,opt,name=type,proto3" json:"type,omitempty"`
	Owner                string   `protobuf:"bytes,5,opt,name=owner,proto3" json:"owner,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqStyleAdd) Reset()         { *m = ReqStyleAdd{} }
func (m *ReqStyleAdd) String() string { return proto.CompactTextString(m) }
func (*ReqStyleAdd) ProtoMessage()    {}
func (*ReqStyleAdd) Descriptor() ([]byte, []int) {
	return fileDescriptor_c94d61fa26c563fe, []int{1}
}

func (m *ReqStyleAdd) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqStyleAdd.Unmarshal(m, b)
}
func (m *ReqStyleAdd) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqStyleAdd.Marshal(b, m, deterministic)
}
func (m *ReqStyleAdd) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqStyleAdd.Merge(m, src)
}
func (m *ReqStyleAdd) XXX_Size() int {
	return xxx_messageInfo_ReqStyleAdd.Size(m)
}
func (m *ReqStyleAdd) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqStyleAdd.DiscardUnknown(m)
}

var xxx_messageInfo_ReqStyleAdd proto.InternalMessageInfo

func (m *ReqStyleAdd) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ReqStyleAdd) GetRemark() string {
	if m != nil {
		return m.Remark
	}
	return ""
}

func (m *ReqStyleAdd) GetOperator() string {
	if m != nil {
		return m.Operator
	}
	return ""
}

func (m *ReqStyleAdd) GetType() uint32 {
	if m != nil {
		return m.Type
	}
	return 0
}

func (m *ReqStyleAdd) GetOwner() string {
	if m != nil {
		return m.Owner
	}
	return ""
}

type ReqStyleUpdate struct {
	Uid                  string   `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Remark               string   `protobuf:"bytes,3,opt,name=remark,proto3" json:"remark,omitempty"`
	Type                 uint32   `protobuf:"varint,4,opt,name=type,proto3" json:"type,omitempty"`
	Operator             string   `protobuf:"bytes,5,opt,name=operator,proto3" json:"operator,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqStyleUpdate) Reset()         { *m = ReqStyleUpdate{} }
func (m *ReqStyleUpdate) String() string { return proto.CompactTextString(m) }
func (*ReqStyleUpdate) ProtoMessage()    {}
func (*ReqStyleUpdate) Descriptor() ([]byte, []int) {
	return fileDescriptor_c94d61fa26c563fe, []int{2}
}

func (m *ReqStyleUpdate) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqStyleUpdate.Unmarshal(m, b)
}
func (m *ReqStyleUpdate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqStyleUpdate.Marshal(b, m, deterministic)
}
func (m *ReqStyleUpdate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqStyleUpdate.Merge(m, src)
}
func (m *ReqStyleUpdate) XXX_Size() int {
	return xxx_messageInfo_ReqStyleUpdate.Size(m)
}
func (m *ReqStyleUpdate) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqStyleUpdate.DiscardUnknown(m)
}

var xxx_messageInfo_ReqStyleUpdate proto.InternalMessageInfo

func (m *ReqStyleUpdate) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *ReqStyleUpdate) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ReqStyleUpdate) GetRemark() string {
	if m != nil {
		return m.Remark
	}
	return ""
}

func (m *ReqStyleUpdate) GetType() uint32 {
	if m != nil {
		return m.Type
	}
	return 0
}

func (m *ReqStyleUpdate) GetOperator() string {
	if m != nil {
		return m.Operator
	}
	return ""
}

type ReplyStyleInfo struct {
	Status               *ReplyStatus `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Info                 *StyleInfo   `protobuf:"bytes,2,opt,name=info,proto3" json:"info,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *ReplyStyleInfo) Reset()         { *m = ReplyStyleInfo{} }
func (m *ReplyStyleInfo) String() string { return proto.CompactTextString(m) }
func (*ReplyStyleInfo) ProtoMessage()    {}
func (*ReplyStyleInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_c94d61fa26c563fe, []int{3}
}

func (m *ReplyStyleInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReplyStyleInfo.Unmarshal(m, b)
}
func (m *ReplyStyleInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReplyStyleInfo.Marshal(b, m, deterministic)
}
func (m *ReplyStyleInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReplyStyleInfo.Merge(m, src)
}
func (m *ReplyStyleInfo) XXX_Size() int {
	return xxx_messageInfo_ReplyStyleInfo.Size(m)
}
func (m *ReplyStyleInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_ReplyStyleInfo.DiscardUnknown(m)
}

var xxx_messageInfo_ReplyStyleInfo proto.InternalMessageInfo

func (m *ReplyStyleInfo) GetStatus() *ReplyStatus {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *ReplyStyleInfo) GetInfo() *StyleInfo {
	if m != nil {
		return m.Info
	}
	return nil
}

type ReplyStyleList struct {
	Status               *ReplyStatus `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	List                 []*StyleInfo `protobuf:"bytes,2,rep,name=list,proto3" json:"list,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *ReplyStyleList) Reset()         { *m = ReplyStyleList{} }
func (m *ReplyStyleList) String() string { return proto.CompactTextString(m) }
func (*ReplyStyleList) ProtoMessage()    {}
func (*ReplyStyleList) Descriptor() ([]byte, []int) {
	return fileDescriptor_c94d61fa26c563fe, []int{4}
}

func (m *ReplyStyleList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReplyStyleList.Unmarshal(m, b)
}
func (m *ReplyStyleList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReplyStyleList.Marshal(b, m, deterministic)
}
func (m *ReplyStyleList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReplyStyleList.Merge(m, src)
}
func (m *ReplyStyleList) XXX_Size() int {
	return xxx_messageInfo_ReplyStyleList.Size(m)
}
func (m *ReplyStyleList) XXX_DiscardUnknown() {
	xxx_messageInfo_ReplyStyleList.DiscardUnknown(m)
}

var xxx_messageInfo_ReplyStyleList proto.InternalMessageInfo

func (m *ReplyStyleList) GetStatus() *ReplyStatus {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *ReplyStyleList) GetList() []*StyleInfo {
	if m != nil {
		return m.List
	}
	return nil
}

func init() {
	proto.RegisterType((*StyleInfo)(nil), "omo.msp.album.StyleInfo")
	proto.RegisterType((*ReqStyleAdd)(nil), "omo.msp.album.ReqStyleAdd")
	proto.RegisterType((*ReqStyleUpdate)(nil), "omo.msp.album.ReqStyleUpdate")
	proto.RegisterType((*ReplyStyleInfo)(nil), "omo.msp.album.ReplyStyleInfo")
	proto.RegisterType((*ReplyStyleList)(nil), "omo.msp.album.ReplyStyleList")
}

func init() {
	proto.RegisterFile("proto/album/style.proto", fileDescriptor_c94d61fa26c563fe)
}

var fileDescriptor_c94d61fa26c563fe = []byte{
	// 596 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x55, 0xc1, 0x6e, 0xd3, 0x4c,
	0x10, 0x8e, 0xed, 0xc4, 0x6d, 0xc6, 0x49, 0xfe, 0x5f, 0x2b, 0x04, 0xab, 0xa8, 0x95, 0x2c, 0x9f,
	0x72, 0x40, 0xa9, 0x64, 0x9e, 0x20, 0x81, 0x34, 0x02, 0x81, 0xa8, 0x1c, 0x71, 0xe1, 0xe6, 0xd8,
	0x53, 0x6a, 0x61, 0x7b, 0xcd, 0xee, 0x3a, 0x28, 0x1c, 0xe0, 0x51, 0x79, 0x01, 0x1e, 0x02, 0xed,
	0xda, 0x09, 0x49, 0xeb, 0x34, 0x28, 0xdc, 0xf6, 0x9b, 0xf9, 0xf6, 0x9b, 0x6f, 0x66, 0x56, 0x36,
	0x3c, 0x2b, 0x38, 0x93, 0xec, 0x2a, 0x4c, 0x97, 0x65, 0x76, 0x25, 0xe4, 0x3a, 0xc5, 0xb1, 0x8e,
	0x90, 0x3e, 0xcb, 0xd8, 0x38, 0x13, 0xc5, 0x58, 0xa7, 0x86, 0x74, 0x97, 0x17, 0xb1, 0x2c, 0x63,
	0x79, 0x45, 0xf4, 0x7e, 0x9a, 0xd0, 0x5d, 0xa8, 0x8b, 0xaf, 0xf3, 0x5b, 0x46, 0xfe, 0x07, 0xab,
	0x4c, 0x62, 0x6a, 0xb8, 0xc6, 0xa8, 0x1b, 0xa8, 0x23, 0x19, 0x80, 0x99, 0xc4, 0xd4, 0x74, 0x8d,
	0x51, 0x3b, 0x30, 0x93, 0x98, 0x50, 0x38, 0x8b, 0x38, 0x86, 0x12, 0x63, 0x6a, 0xb9, 0xc6, 0xc8,
	0x0a, 0x36, 0x50, 0x65, 0xca, 0x22, 0xd6, 0x99, 0x76, 0x95, 0xa9, 0xe1, 0xf6, 0x0e, 0xe3, 0xb4,
	0xa3, 0x95, 0x37, 0x90, 0x0c, 0xe1, 0x9c, 0x15, 0xc8, 0x75, 0xca, 0xd6, 0xa9, 0x2d, 0x26, 0x04,
	0xda, 0x79, 0x98, 0x21, 0x3d, 0xd3, 0x71, 0x7d, 0x26, 0x4f, 0xc1, 0xe6, 0x98, 0x85, 0xfc, 0x33,
	0x3d, 0xd7, 0xd1, 0x1a, 0x29, 0xae, 0x5c, 0x17, 0x48, 0xbb, 0xae, 0x31, 0xea, 0x07, 0xfa, 0x4c,
	0x9e, 0x40, 0x27, 0x62, 0x2b, 0xe4, 0x14, 0x34, 0xb5, 0x02, 0x8a, 0x29, 0x92, 0x6f, 0x48, 0x9d,
	0x8a, 0xa9, 0xce, 0x8a, 0x59, 0xf0, 0x24, 0x42, 0xda, 0xd3, 0xc1, 0x0a, 0x68, 0xcd, 0xf0, 0x93,
	0xa0, 0x7d, 0xd7, 0x52, 0xf5, 0xd5, 0x99, 0xf8, 0xd0, 0x11, 0x29, 0x93, 0x82, 0x0e, 0x5c, 0x6b,
	0xe4, 0xf8, 0x17, 0xe3, 0xbd, 0x31, 0x8f, 0x6f, 0xee, 0x98, 0x64, 0x11, 0x2b, 0xd6, 0x8b, 0x94,
	0xc9, 0xa0, 0xa2, 0x7a, 0x3f, 0xc0, 0x09, 0xf0, 0x8b, 0x9e, 0xf1, 0x24, 0x8e, 0xb7, 0x6d, 0x19,
	0x8d, 0x6d, 0x99, 0x7b, 0x6d, 0xed, 0x8e, 0xc7, 0x7a, 0x38, 0x1e, 0xdd, 0x72, 0x7b, 0xbf, 0x65,
	0xf6, 0x35, 0xc7, 0xcd, 0x98, 0x2b, 0xe0, 0x7d, 0x87, 0xc1, 0xc6, 0xc0, 0x07, 0xbd, 0x91, 0x86,
	0x35, 0x6f, 0x5c, 0x99, 0x8d, 0xae, 0xac, 0xc6, 0x61, 0xef, 0x56, 0xde, 0x75, 0xda, 0xd9, 0x77,
	0xea, 0x71, 0x55, 0xbf, 0x48, 0xd7, 0x7f, 0x9e, 0x99, 0x0f, 0xb6, 0x90, 0xa1, 0x2c, 0x85, 0xb6,
	0xe0, 0xf8, 0xc3, 0x7b, 0x73, 0xac, 0xe9, 0x8a, 0x11, 0xd4, 0x4c, 0xf2, 0x1c, 0xda, 0x49, 0x7e,
	0xcb, 0xb4, 0x43, 0xc7, 0xa7, 0xf7, 0x6e, 0x6c, 0xb5, 0x03, 0xcd, 0xda, 0xaf, 0xf9, 0x36, 0x11,
	0xf2, 0xd4, 0x9a, 0x69, 0x22, 0x24, 0x35, 0xf5, 0xb6, 0x1f, 0xa9, 0xa9, 0x58, 0xfe, 0xaf, 0x0e,
	0xf4, 0x74, 0x6c, 0x81, 0x7c, 0xa5, 0x5e, 0xd0, 0x0c, 0xec, 0x49, 0x1c, 0xbf, 0xcf, 0x91, 0x3c,
	0x2c, 0xb6, 0x7d, 0x10, 0xc3, 0xcb, 0x66, 0x23, 0xb5, 0xb6, 0xd7, 0x22, 0x73, 0x80, 0x6a, 0x6f,
	0xd3, 0x50, 0x20, 0xb9, 0x3c, 0x20, 0x55, 0x51, 0x86, 0xb4, 0x49, 0xad, 0x16, 0x7a, 0x09, 0xdd,
	0x00, 0x33, 0xb6, 0xc2, 0x03, 0x96, 0x4a, 0x14, 0x52, 0x51, 0x1f, 0x15, 0x99, 0x81, 0x3d, 0x47,
	0x79, 0x4c, 0xe1, 0x68, 0x53, 0x33, 0xb0, 0x17, 0x18, 0xf2, 0xe8, 0xee, 0x44, 0x19, 0xb5, 0x53,
	0xaf, 0x45, 0x6e, 0xe0, 0xbf, 0x39, 0x4a, 0x05, 0xa6, 0xeb, 0xeb, 0x24, 0x95, 0xc8, 0xc9, 0x45,
	0xb3, 0x5e, 0x95, 0x3d, 0xae, 0xf8, 0x0e, 0x7a, 0x73, 0x94, 0xea, 0x21, 0x24, 0x42, 0x26, 0xd1,
	0x69, 0x72, 0xf5, 0x65, 0xaf, 0x45, 0xde, 0xc0, 0xa0, 0x5e, 0xde, 0x11, 0x7f, 0x7f, 0xb1, 0xbf,
	0x57, 0x00, 0x93, 0xa2, 0xc0, 0x3c, 0x56, 0x9f, 0x97, 0x43, 0x73, 0x53, 0x6d, 0x34, 0xab, 0xd4,
	0x0d, 0x5e, 0x43, 0x6f, 0x51, 0x2e, 0x25, 0x0f, 0x23, 0xf9, 0x2f, 0x3a, 0xd3, 0xfe, 0x47, 0x67,
	0xe7, 0xaf, 0xb2, 0xb4, 0x35, 0x78, 0xf1, 0x3b, 0x00, 0x00, 0xff, 0xff, 0xc7, 0x10, 0xd8, 0x15,
	0x93, 0x06, 0x00, 0x00,
}
