// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/album/style.proto

package album

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type StyleInfo struct {
	Uid                  string       `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Id                   uint64       `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	Created              int64        `protobuf:"varint,3,opt,name=created,proto3" json:"created,omitempty"`
	Updated              int64        `protobuf:"varint,4,opt,name=updated,proto3" json:"updated,omitempty"`
	Creator              string       `protobuf:"bytes,5,opt,name=creator,proto3" json:"creator,omitempty"`
	Operator             string       `protobuf:"bytes,6,opt,name=operator,proto3" json:"operator,omitempty"`
	Name                 string       `protobuf:"bytes,7,opt,name=name,proto3" json:"name,omitempty"`
	Remark               string       `protobuf:"bytes,8,opt,name=remark,proto3" json:"remark,omitempty"`
	Type                 uint32       `protobuf:"varint,9,opt,name=type,proto3" json:"type,omitempty"`
	Cover                string       `protobuf:"bytes,10,opt,name=cover,proto3" json:"cover,omitempty"`
	Background           string       `protobuf:"bytes,11,opt,name=background,proto3" json:"background,omitempty"`
	Prefix               string       `protobuf:"bytes,12,opt,name=prefix,proto3" json:"prefix,omitempty"`
	Tags                 []string     `protobuf:"bytes,21,rep,name=tags,proto3" json:"tags,omitempty"`
	Scenes               []string     `protobuf:"bytes,22,rep,name=scenes,proto3" json:"scenes,omitempty"`
	Slots                []*StyleSlot `protobuf:"bytes,31,rep,name=slots,proto3" json:"slots,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *StyleInfo) Reset()         { *m = StyleInfo{} }
func (m *StyleInfo) String() string { return proto.CompactTextString(m) }
func (*StyleInfo) ProtoMessage()    {}
func (*StyleInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_c94d61fa26c563fe, []int{0}
}

func (m *StyleInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StyleInfo.Unmarshal(m, b)
}
func (m *StyleInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StyleInfo.Marshal(b, m, deterministic)
}
func (m *StyleInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StyleInfo.Merge(m, src)
}
func (m *StyleInfo) XXX_Size() int {
	return xxx_messageInfo_StyleInfo.Size(m)
}
func (m *StyleInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_StyleInfo.DiscardUnknown(m)
}

var xxx_messageInfo_StyleInfo proto.InternalMessageInfo

func (m *StyleInfo) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *StyleInfo) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *StyleInfo) GetCreated() int64 {
	if m != nil {
		return m.Created
	}
	return 0
}

func (m *StyleInfo) GetUpdated() int64 {
	if m != nil {
		return m.Updated
	}
	return 0
}

func (m *StyleInfo) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *StyleInfo) GetOperator() string {
	if m != nil {
		return m.Operator
	}
	return ""
}

func (m *StyleInfo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *StyleInfo) GetRemark() string {
	if m != nil {
		return m.Remark
	}
	return ""
}

func (m *StyleInfo) GetType() uint32 {
	if m != nil {
		return m.Type
	}
	return 0
}

func (m *StyleInfo) GetCover() string {
	if m != nil {
		return m.Cover
	}
	return ""
}

func (m *StyleInfo) GetBackground() string {
	if m != nil {
		return m.Background
	}
	return ""
}

func (m *StyleInfo) GetPrefix() string {
	if m != nil {
		return m.Prefix
	}
	return ""
}

func (m *StyleInfo) GetTags() []string {
	if m != nil {
		return m.Tags
	}
	return nil
}

func (m *StyleInfo) GetScenes() []string {
	if m != nil {
		return m.Scenes
	}
	return nil
}

func (m *StyleInfo) GetSlots() []*StyleSlot {
	if m != nil {
		return m.Slots
	}
	return nil
}

type StyleSlot struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	X                    int32    `protobuf:"varint,2,opt,name=x,proto3" json:"x,omitempty"`
	Y                    int32    `protobuf:"varint,3,opt,name=y,proto3" json:"y,omitempty"`
	Width                uint32   `protobuf:"varint,4,opt,name=width,proto3" json:"width,omitempty"`
	Height               uint32   `protobuf:"varint,5,opt,name=height,proto3" json:"height,omitempty"`
	Bold                 uint32   `protobuf:"varint,6,opt,name=bold,proto3" json:"bold,omitempty"`
	Size                 uint32   `protobuf:"varint,7,opt,name=size,proto3" json:"size,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StyleSlot) Reset()         { *m = StyleSlot{} }
func (m *StyleSlot) String() string { return proto.CompactTextString(m) }
func (*StyleSlot) ProtoMessage()    {}
func (*StyleSlot) Descriptor() ([]byte, []int) {
	return fileDescriptor_c94d61fa26c563fe, []int{1}
}

func (m *StyleSlot) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StyleSlot.Unmarshal(m, b)
}
func (m *StyleSlot) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StyleSlot.Marshal(b, m, deterministic)
}
func (m *StyleSlot) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StyleSlot.Merge(m, src)
}
func (m *StyleSlot) XXX_Size() int {
	return xxx_messageInfo_StyleSlot.Size(m)
}
func (m *StyleSlot) XXX_DiscardUnknown() {
	xxx_messageInfo_StyleSlot.DiscardUnknown(m)
}

var xxx_messageInfo_StyleSlot proto.InternalMessageInfo

func (m *StyleSlot) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *StyleSlot) GetX() int32 {
	if m != nil {
		return m.X
	}
	return 0
}

func (m *StyleSlot) GetY() int32 {
	if m != nil {
		return m.Y
	}
	return 0
}

func (m *StyleSlot) GetWidth() uint32 {
	if m != nil {
		return m.Width
	}
	return 0
}

func (m *StyleSlot) GetHeight() uint32 {
	if m != nil {
		return m.Height
	}
	return 0
}

func (m *StyleSlot) GetBold() uint32 {
	if m != nil {
		return m.Bold
	}
	return 0
}

func (m *StyleSlot) GetSize() uint32 {
	if m != nil {
		return m.Size
	}
	return 0
}

type ReqStyleAdd struct {
	Name                 string       `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Remark               string       `protobuf:"bytes,2,opt,name=remark,proto3" json:"remark,omitempty"`
	Operator             string       `protobuf:"bytes,3,opt,name=operator,proto3" json:"operator,omitempty"`
	Type                 uint32       `protobuf:"varint,4,opt,name=type,proto3" json:"type,omitempty"`
	Background           string       `protobuf:"bytes,5,opt,name=background,proto3" json:"background,omitempty"`
	Cover                string       `protobuf:"bytes,6,opt,name=cover,proto3" json:"cover,omitempty"`
	Prefix               string       `protobuf:"bytes,7,opt,name=prefix,proto3" json:"prefix,omitempty"`
	Tags                 []string     `protobuf:"bytes,15,rep,name=tags,proto3" json:"tags,omitempty"`
	Scenes               []string     `protobuf:"bytes,16,rep,name=scenes,proto3" json:"scenes,omitempty"`
	Slots                []*StyleSlot `protobuf:"bytes,21,rep,name=slots,proto3" json:"slots,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *ReqStyleAdd) Reset()         { *m = ReqStyleAdd{} }
func (m *ReqStyleAdd) String() string { return proto.CompactTextString(m) }
func (*ReqStyleAdd) ProtoMessage()    {}
func (*ReqStyleAdd) Descriptor() ([]byte, []int) {
	return fileDescriptor_c94d61fa26c563fe, []int{2}
}

func (m *ReqStyleAdd) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqStyleAdd.Unmarshal(m, b)
}
func (m *ReqStyleAdd) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqStyleAdd.Marshal(b, m, deterministic)
}
func (m *ReqStyleAdd) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqStyleAdd.Merge(m, src)
}
func (m *ReqStyleAdd) XXX_Size() int {
	return xxx_messageInfo_ReqStyleAdd.Size(m)
}
func (m *ReqStyleAdd) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqStyleAdd.DiscardUnknown(m)
}

var xxx_messageInfo_ReqStyleAdd proto.InternalMessageInfo

func (m *ReqStyleAdd) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ReqStyleAdd) GetRemark() string {
	if m != nil {
		return m.Remark
	}
	return ""
}

func (m *ReqStyleAdd) GetOperator() string {
	if m != nil {
		return m.Operator
	}
	return ""
}

func (m *ReqStyleAdd) GetType() uint32 {
	if m != nil {
		return m.Type
	}
	return 0
}

func (m *ReqStyleAdd) GetBackground() string {
	if m != nil {
		return m.Background
	}
	return ""
}

func (m *ReqStyleAdd) GetCover() string {
	if m != nil {
		return m.Cover
	}
	return ""
}

func (m *ReqStyleAdd) GetPrefix() string {
	if m != nil {
		return m.Prefix
	}
	return ""
}

func (m *ReqStyleAdd) GetTags() []string {
	if m != nil {
		return m.Tags
	}
	return nil
}

func (m *ReqStyleAdd) GetScenes() []string {
	if m != nil {
		return m.Scenes
	}
	return nil
}

func (m *ReqStyleAdd) GetSlots() []*StyleSlot {
	if m != nil {
		return m.Slots
	}
	return nil
}

type ReqStyleUpdate struct {
	Uid                  string       `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Name                 string       `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Remark               string       `protobuf:"bytes,3,opt,name=remark,proto3" json:"remark,omitempty"`
	Type                 uint32       `protobuf:"varint,4,opt,name=type,proto3" json:"type,omitempty"`
	Operator             string       `protobuf:"bytes,5,opt,name=operator,proto3" json:"operator,omitempty"`
	Background           string       `protobuf:"bytes,6,opt,name=background,proto3" json:"background,omitempty"`
	Tags                 []string     `protobuf:"bytes,15,rep,name=tags,proto3" json:"tags,omitempty"`
	Scenes               []string     `protobuf:"bytes,16,rep,name=scenes,proto3" json:"scenes,omitempty"`
	Slots                []*StyleSlot `protobuf:"bytes,21,rep,name=slots,proto3" json:"slots,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *ReqStyleUpdate) Reset()         { *m = ReqStyleUpdate{} }
func (m *ReqStyleUpdate) String() string { return proto.CompactTextString(m) }
func (*ReqStyleUpdate) ProtoMessage()    {}
func (*ReqStyleUpdate) Descriptor() ([]byte, []int) {
	return fileDescriptor_c94d61fa26c563fe, []int{3}
}

func (m *ReqStyleUpdate) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqStyleUpdate.Unmarshal(m, b)
}
func (m *ReqStyleUpdate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqStyleUpdate.Marshal(b, m, deterministic)
}
func (m *ReqStyleUpdate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqStyleUpdate.Merge(m, src)
}
func (m *ReqStyleUpdate) XXX_Size() int {
	return xxx_messageInfo_ReqStyleUpdate.Size(m)
}
func (m *ReqStyleUpdate) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqStyleUpdate.DiscardUnknown(m)
}

var xxx_messageInfo_ReqStyleUpdate proto.InternalMessageInfo

func (m *ReqStyleUpdate) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *ReqStyleUpdate) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ReqStyleUpdate) GetRemark() string {
	if m != nil {
		return m.Remark
	}
	return ""
}

func (m *ReqStyleUpdate) GetType() uint32 {
	if m != nil {
		return m.Type
	}
	return 0
}

func (m *ReqStyleUpdate) GetOperator() string {
	if m != nil {
		return m.Operator
	}
	return ""
}

func (m *ReqStyleUpdate) GetBackground() string {
	if m != nil {
		return m.Background
	}
	return ""
}

func (m *ReqStyleUpdate) GetTags() []string {
	if m != nil {
		return m.Tags
	}
	return nil
}

func (m *ReqStyleUpdate) GetScenes() []string {
	if m != nil {
		return m.Scenes
	}
	return nil
}

func (m *ReqStyleUpdate) GetSlots() []*StyleSlot {
	if m != nil {
		return m.Slots
	}
	return nil
}

type ReplyStyleInfo struct {
	Status               *ReplyStatus `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Info                 *StyleInfo   `protobuf:"bytes,2,opt,name=info,proto3" json:"info,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *ReplyStyleInfo) Reset()         { *m = ReplyStyleInfo{} }
func (m *ReplyStyleInfo) String() string { return proto.CompactTextString(m) }
func (*ReplyStyleInfo) ProtoMessage()    {}
func (*ReplyStyleInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_c94d61fa26c563fe, []int{4}
}

func (m *ReplyStyleInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReplyStyleInfo.Unmarshal(m, b)
}
func (m *ReplyStyleInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReplyStyleInfo.Marshal(b, m, deterministic)
}
func (m *ReplyStyleInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReplyStyleInfo.Merge(m, src)
}
func (m *ReplyStyleInfo) XXX_Size() int {
	return xxx_messageInfo_ReplyStyleInfo.Size(m)
}
func (m *ReplyStyleInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_ReplyStyleInfo.DiscardUnknown(m)
}

var xxx_messageInfo_ReplyStyleInfo proto.InternalMessageInfo

func (m *ReplyStyleInfo) GetStatus() *ReplyStatus {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *ReplyStyleInfo) GetInfo() *StyleInfo {
	if m != nil {
		return m.Info
	}
	return nil
}

type ReplyStyleList struct {
	Status               *ReplyStatus `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Total                uint32       `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	Pages                uint32       `protobuf:"varint,3,opt,name=pages,proto3" json:"pages,omitempty"`
	List                 []*StyleInfo `protobuf:"bytes,11,rep,name=list,proto3" json:"list,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *ReplyStyleList) Reset()         { *m = ReplyStyleList{} }
func (m *ReplyStyleList) String() string { return proto.CompactTextString(m) }
func (*ReplyStyleList) ProtoMessage()    {}
func (*ReplyStyleList) Descriptor() ([]byte, []int) {
	return fileDescriptor_c94d61fa26c563fe, []int{5}
}

func (m *ReplyStyleList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReplyStyleList.Unmarshal(m, b)
}
func (m *ReplyStyleList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReplyStyleList.Marshal(b, m, deterministic)
}
func (m *ReplyStyleList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReplyStyleList.Merge(m, src)
}
func (m *ReplyStyleList) XXX_Size() int {
	return xxx_messageInfo_ReplyStyleList.Size(m)
}
func (m *ReplyStyleList) XXX_DiscardUnknown() {
	xxx_messageInfo_ReplyStyleList.DiscardUnknown(m)
}

var xxx_messageInfo_ReplyStyleList proto.InternalMessageInfo

func (m *ReplyStyleList) GetStatus() *ReplyStatus {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *ReplyStyleList) GetTotal() uint32 {
	if m != nil {
		return m.Total
	}
	return 0
}

func (m *ReplyStyleList) GetPages() uint32 {
	if m != nil {
		return m.Pages
	}
	return 0
}

func (m *ReplyStyleList) GetList() []*StyleInfo {
	if m != nil {
		return m.List
	}
	return nil
}

func init() {
	proto.RegisterType((*StyleInfo)(nil), "omo.msp.album.StyleInfo")
	proto.RegisterType((*StyleSlot)(nil), "omo.msp.album.StyleSlot")
	proto.RegisterType((*ReqStyleAdd)(nil), "omo.msp.album.ReqStyleAdd")
	proto.RegisterType((*ReqStyleUpdate)(nil), "omo.msp.album.ReqStyleUpdate")
	proto.RegisterType((*ReplyStyleInfo)(nil), "omo.msp.album.ReplyStyleInfo")
	proto.RegisterType((*ReplyStyleList)(nil), "omo.msp.album.ReplyStyleList")
}

func init() {
	proto.RegisterFile("proto/album/style.proto", fileDescriptor_c94d61fa26c563fe)
}

var fileDescriptor_c94d61fa26c563fe = []byte{
	// 713 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x55, 0xc1, 0x6e, 0xda, 0x4a,
	0x14, 0x8d, 0x31, 0x76, 0xc2, 0x05, 0x27, 0xd1, 0x28, 0xc9, 0x1b, 0xa1, 0x97, 0xf7, 0x10, 0x2b,
	0x16, 0x4f, 0x44, 0xe2, 0x7d, 0x41, 0x52, 0xa5, 0xa8, 0x55, 0xab, 0x56, 0x13, 0x75, 0xd3, 0x9d,
	0xb1, 0x27, 0x60, 0x61, 0x7b, 0x5c, 0xcf, 0x90, 0xc6, 0xdd, 0xf5, 0x0b, 0xba, 0xe8, 0xbe, 0x9f,
	0xd6, 0x0f, 0xe9, 0xaa, 0x9a, 0x3b, 0x86, 0x98, 0x60, 0x4a, 0x15, 0xa9, 0xbb, 0x39, 0xf7, 0x1e,
	0x9f, 0x7b, 0xe7, 0x9c, 0x21, 0x81, 0xbf, 0xb2, 0x5c, 0x28, 0x71, 0xe1, 0xc7, 0x93, 0x45, 0x72,
	0x21, 0x55, 0x11, 0xf3, 0x21, 0x56, 0x88, 0x27, 0x12, 0x31, 0x4c, 0x64, 0x36, 0xc4, 0x56, 0x97,
	0x56, 0x79, 0x81, 0x48, 0x12, 0x91, 0x1a, 0x62, 0xff, 0xb3, 0x0d, 0xad, 0x1b, 0xfd, 0xe1, 0x8b,
	0xf4, 0x56, 0x90, 0x63, 0xb0, 0x17, 0x51, 0x48, 0xad, 0x9e, 0x35, 0x68, 0x31, 0x7d, 0x24, 0x87,
	0xd0, 0x88, 0x42, 0xda, 0xe8, 0x59, 0x83, 0x26, 0x6b, 0x44, 0x21, 0xa1, 0xb0, 0x1f, 0xe4, 0xdc,
	0x57, 0x3c, 0xa4, 0x76, 0xcf, 0x1a, 0xd8, 0x6c, 0x09, 0x75, 0x67, 0x91, 0x85, 0xd8, 0x69, 0x9a,
	0x4e, 0x09, 0x57, 0xdf, 0x88, 0x9c, 0x3a, 0xa8, 0xbc, 0x84, 0xa4, 0x0b, 0x07, 0x22, 0xe3, 0x39,
	0xb6, 0x5c, 0x6c, 0xad, 0x30, 0x21, 0xd0, 0x4c, 0xfd, 0x84, 0xd3, 0x7d, 0xac, 0xe3, 0x99, 0x9c,
	0x81, 0x9b, 0xf3, 0xc4, 0xcf, 0xe7, 0xf4, 0x00, 0xab, 0x25, 0xd2, 0x5c, 0x55, 0x64, 0x9c, 0xb6,
	0x7a, 0xd6, 0xc0, 0x63, 0x78, 0x26, 0x27, 0xe0, 0x04, 0xe2, 0x8e, 0xe7, 0x14, 0x90, 0x6a, 0x00,
	0xf9, 0x07, 0x60, 0xe2, 0x07, 0xf3, 0x69, 0x2e, 0x16, 0x69, 0x48, 0xdb, 0xd8, 0xaa, 0x54, 0xf4,
	0x84, 0x2c, 0xe7, 0xb7, 0xd1, 0x3d, 0xed, 0x98, 0x09, 0x06, 0xe1, 0x04, 0x7f, 0x2a, 0xe9, 0x69,
	0xcf, 0xd6, 0xdb, 0xe8, 0xb3, 0xe6, 0xca, 0x80, 0xa7, 0x5c, 0xd2, 0x33, 0xac, 0x96, 0x88, 0x0c,
	0xc1, 0x91, 0xb1, 0x50, 0x92, 0xfe, 0xdb, 0xb3, 0x07, 0xed, 0x11, 0x1d, 0xae, 0x85, 0x31, 0x44,
	0xbb, 0x6f, 0x62, 0xa1, 0x98, 0xa1, 0xf5, 0xbf, 0x58, 0x65, 0x06, 0xba, 0xa8, 0x33, 0x98, 0xf3,
	0x62, 0x99, 0xc1, 0x9c, 0x17, 0xa4, 0x03, 0xd6, 0x3d, 0x46, 0xe0, 0x30, 0xeb, 0x5e, 0xa3, 0x02,
	0xbd, 0x77, 0x98, 0x55, 0xe8, 0x5b, 0x7e, 0x8c, 0x42, 0x35, 0x43, 0xcf, 0x3d, 0x66, 0x80, 0xde,
	0x6c, 0xc6, 0xa3, 0xe9, 0x4c, 0xa1, 0xe1, 0x1e, 0x2b, 0x91, 0xbe, 0xc5, 0x44, 0xc4, 0x21, 0x7a,
	0xed, 0x31, 0x3c, 0xeb, 0x9a, 0x8c, 0x3e, 0x19, 0x9f, 0x3d, 0x86, 0xe7, 0xfe, 0xd7, 0x06, 0xb4,
	0x19, 0xff, 0x80, 0x4b, 0x5d, 0x86, 0xe1, 0x2a, 0x0b, 0xab, 0x36, 0x8b, 0xc6, 0x5a, 0x16, 0xd5,
	0x4c, 0xed, 0xcd, 0x4c, 0x31, 0xa7, 0x66, 0x25, 0xa7, 0xf5, 0x44, 0x9c, 0x8d, 0x44, 0x56, 0x39,
	0xba, 0xd5, 0x1c, 0x1f, 0x72, 0xda, 0xaf, 0xcd, 0xe9, 0xa8, 0x36, 0xa7, 0xe3, 0xfa, 0x9c, 0x4e,
	0x7f, 0x2f, 0xa7, 0x1f, 0x16, 0x1c, 0x2e, 0x5d, 0x79, 0x87, 0x6f, 0xbb, 0xe6, 0x07, 0xb3, 0xb4,
	0xaa, 0x51, 0x6b, 0x95, 0x5d, 0xfb, 0x6c, 0xab, 0x76, 0x54, 0xed, 0x73, 0x1e, 0xd9, 0xb7, 0x6e,
	0x95, 0xbb, 0x61, 0xd5, 0x9f, 0xbc, 0x7c, 0xae, 0xef, 0x9e, 0xc5, 0xc5, 0xc3, 0x1f, 0x8b, 0x11,
	0xb8, 0x52, 0xf9, 0x6a, 0x21, 0xf1, 0xfa, 0xed, 0x51, 0xf7, 0x91, 0x44, 0x49, 0xd7, 0x0c, 0x56,
	0x32, 0xc9, 0x7f, 0xd0, 0x8c, 0xd2, 0x5b, 0x81, 0xee, 0x6c, 0x19, 0xaa, 0xb5, 0x19, 0xb2, 0xfa,
	0xdf, 0xac, 0xea, 0xd0, 0x57, 0x91, 0x54, 0x4f, 0x1a, 0x7a, 0x02, 0x8e, 0x12, 0xca, 0x8f, 0x71,
	0xaa, 0xc7, 0x0c, 0xd0, 0xd5, 0xcc, 0x9f, 0x72, 0x89, 0x99, 0x78, 0xcc, 0x00, 0xbd, 0x60, 0x1c,
	0x49, 0x45, 0xdb, 0xdb, 0x5d, 0x31, 0x0b, 0x6a, 0xd6, 0xe8, 0x7b, 0x13, 0x3a, 0xc6, 0x29, 0x9e,
	0xdf, 0x45, 0x01, 0x27, 0xd7, 0xe0, 0x5e, 0x86, 0xe1, 0x9b, 0x94, 0x93, 0xcd, 0xc5, 0x56, 0x3f,
	0xa7, 0xee, 0x79, 0xfd, 0xd2, 0xa5, 0x76, 0x7f, 0x8f, 0x8c, 0x01, 0xcc, 0x03, 0xbb, 0xf2, 0x25,
	0x27, 0xe7, 0x5b, 0xa4, 0x0c, 0xa5, 0x4b, 0xeb, 0xd4, 0x4a, 0xa1, 0x67, 0xd0, 0x62, 0x3c, 0x11,
	0x77, 0x7c, 0xcb, 0x4a, 0x0b, 0x2e, 0x95, 0xa6, 0xfe, 0x52, 0xe4, 0x1a, 0xdc, 0x31, 0x57, 0xbb,
	0x14, 0x76, 0x5e, 0xea, 0x1a, 0xdc, 0x1b, 0xee, 0xe7, 0xc1, 0xec, 0x89, 0x32, 0x3a, 0xff, 0xfe,
	0x1e, 0x79, 0x0b, 0x47, 0x63, 0xae, 0x34, 0xb8, 0x2a, 0x9e, 0x47, 0xb1, 0xe2, 0x39, 0xf9, 0xbb,
	0x5e, 0xcf, 0x74, 0x77, 0x2b, 0xbe, 0x86, 0xce, 0x98, 0x2b, 0xfd, 0x68, 0x22, 0xa9, 0xa2, 0xe0,
	0x69, 0x72, 0xe5, 0xc7, 0xfd, 0x3d, 0xf2, 0x12, 0x0e, 0xcb, 0xf0, 0x76, 0xec, 0xb7, 0x3b, 0xbf,
	0x2b, 0xef, 0x7d, 0xbb, 0xf2, 0xaf, 0x7b, 0xe2, 0x22, 0xf8, 0xff, 0x67, 0x00, 0x00, 0x00, 0xff,
	0xff, 0x4d, 0xfb, 0x0d, 0x07, 0xf8, 0x07, 0x00, 0x00,
}
